// Generated by Skyramp v1.3.12 on 2026-03-13 17:48:58.448808701 +0000 UTC m=+142.805555355
// Command: skyramp generate smoke rest http://localhost:8055/math/add \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params a=2,b=3 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// smoke test for /math/add GET
test('testAddGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const addGetResponse = await client.sendRequest({
        url: URL,
        path: "/math/add",
        method: "GET",
        headers: headers,
        queryParams: {
            "a": "2",
            "b": "3"
        }
    });

    // Generated Assertions
    expect(checkStatusCode(addGetResponse, "20X"), 'status code').toBeTruthy();
});
