// Generated by Skyramp v1.3.12 on 2026-03-13 17:49:34.915775016 +0000 UTC m=+179.272521680
// Command: skyramp generate fuzz rest http://localhost:8055/math/add \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params a=2,b=3 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /math/add GET
test('testAddGet', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Fuzz strategies
    const addGetFuzzedQuery: Record<string, string|number|boolean|object> = {
        "a": "2",
        "b": "3"
    };
    // Fuzz status codes
    const expectedAddGetFuzzedQueryStatusCode: Record<string, string> = {
        "a": "40x",
        "b": "40x"
    };

    // Execute Request
    let addGetResponse = await client.sendRequest({
        url:URL,
        path:"/math/add",
        method:"GET",
        headers:headers,
        queryParams:{
            "a": "2",
            "b": "3"
        },
        expectedCode:"20x"
    });


    for (const key of iterate(addGetFuzzedQuery)) {
        let query_params: Record<string, string> = {
            "a": "2",
            "b": "3"
        };
        query_params[key] = addGetFuzzedQuery[key];

        // Execute Request
        addGetResponse = await client.sendRequest({
            url:URL,
            path:"/math/add",
            method:"GET",
            headers:headers,
            queryParams:query_params,
            expectedCode:expectedAddGetFuzzedQueryStatusCode[key],
            description:`Fuzzing query param ${key} to ${addGetFuzzedQuery[key]}`
        });


        query_params = {
            "a": "2",
            "b": "3"
        };
        query_params[key] = "";

        // Execute Request
        addGetResponse = await client.sendRequest({
            url:URL,
            path:"/math/add",
            method:"GET",
            headers:headers,
            queryParams:query_params,
            expectedCode:expectedAddGetFuzzedQueryStatusCode[key],
            description:`Fuzzing query param ${key} to ""`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

