// Generated by Skyramp v1.3.12 on 2026-03-13 17:49:35.018782948 +0000 UTC m=+179.375529602
// Command: skyramp generate load rest http://localhost:8055/math/add \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params a=2,b=3 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';
import { AsyncScenario, LoadTestConfig } from '@skyramp/skyramp';
// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testAddGet', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Add Request to Scenario
    let addGetResponse = scenario.addAsyncRequest({
        name: "add_GET",
        url: URL,
        path: "/math/add",
        method: "GET",
        headers: headers,
        queryParams: {
            "a": "2",
            "b": "3"
        },
        expectedCode: "20x"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

