// Generated by Skyramp v1.3.13 on 2026-03-18 01:48:29.210167863 +0000 UTC m=+129.701950071
// Command: skyramp generate contract rest http://localhost:8055/archive/test_archive_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/test_archive_items PATCH
test('testTestArchiveItemsPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testArchiveItemsPatchRequestBody: string = `{
        "keys": [
            1
        ],
        "status_field": "status"
    }`;

    // Execute Request
    const testArchiveItemsPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/test_archive_items",
        method: "PATCH",
        body: testArchiveItemsPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(testArchiveItemsPatchResponse, "20x"), 'status code').toBeTruthy();
});
