// Generated by Skyramp v1.3.13 on 2026-03-16 22:57:41.224118759 +0000 UTC m=+174.903438677
// Command: skyramp generate contract rest http://localhost:8055/archive/archive_test_articles \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_null_status_field_PATCH_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":null} \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/archive_test_articles PATCH
test('testArchiveTestArticlesPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archiveTestArticlesPatchRequestBody: string = `{
        "keys": [
            1
        ],
        "status_field": null
    }`;

    // Execute Request
    const archiveTestArticlesPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/archive_test_articles",
        method: "PATCH",
        body: archiveTestArticlesPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archiveTestArticlesPatchResponse.statusCode, 'status code').toBe(400);
});
