// Generated by Skyramp v1.3.13 on 2026-03-18 00:32:10.912429212 +0000 UTC m=+124.041208390
// Command: skyramp generate contract rest http://localhost:8055/archive/skyramp_archive_test \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/skyramp_archive_test PATCH
test('testSkyrampArchiveTestPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const skyrampArchiveTestPatchRequestBody: string = `{
        "keys": [
            1
        ],
        "status_field": "status"
    }`;

    // Execute Request
    const skyrampArchiveTestPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/skyramp_archive_test",
        method: "PATCH",
        body: skyrampArchiveTestPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(skyrampArchiveTestPatchResponse, "20x"), 'status code').toBeTruthy();
});
