// Generated by Skyramp v1.3.13 on 2026-03-16 22:03:01.482876908 +0000 UTC m=+194.832245673
// Command: skyramp generate contract rest http://localhost:8055/archive/directus_users \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_system_collection_PATCH_forbidden_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--response-status-code 403 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/directus_users PATCH
test('testDirectusUsersPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const directusUsersPatchRequestBody: string = `{
        "keys": [
            1
        ],
        "status_field": "status"
    }`;

    // Execute Request
    const directusUsersPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/directus_users",
        method: "PATCH",
        body: directusUsersPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusUsersPatchResponse.statusCode, 'status code').toBe(403);
});
