// Generated by Skyramp v1.3.13 on 2026-03-18 00:32:08.476685901 +0000 UTC m=+121.605465079
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output archive_workflow_integration.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_archive-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "skyramp_archive_test";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "skyramp_archive_test",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true,
                        "interface": "input",
                        "readonly": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "status",
                    "meta": {
                        "interface": "select-dropdown",
                        "options": {
                            "choices": [
                                {
                                    "text": "Draft",
                                    "value": "draft"
                                },
                                {
                                    "text": "Archived",
                                    "value": "archived"
                                }
                            ]
                        },
                        "width": "full"
                    },
                    "schema": {
                        "default_value": "draft"
                    },
                    "type": "string"
                }
            ]
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "status": "draft"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const archivePatchRequestBody = `{
            "keys": [
                ${getResponseValue(itemsPostResponse, "data.id")}
            ],
            "status_field": "status"
        }`
    
    // Execute Request
    let archivePatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/archive/{archive}",
        method:"PATCH",
        body:archivePatchRequestBody,
        headers:headers,
        pathParams:{"archive": items}
    });

    // Generated Assertions
    expect(archivePatchResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let items1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}/{items_1}",
        method:"GET",
        headers:headers,
        pathParams:{
            "items": items,
            "items_1": getResponseValue(itemsPostResponse, "data.id")
        }
    });

    // Generated Assertions
    expect(items1GetResponse.statusCode, 'status code').toBe(200);
});

