// Generated by Skyramp v1.3.13 on 2026-03-18 00:32:13.800522535 +0000 UTC m=+126.929301723
// Command: skyramp generate fuzz rest http://localhost:8055/archive/skyramp_archive_test \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_fuzz.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /archive/skyramp_archive_test PATCH
test('testSkyrampArchiveTestPatch', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const skyrampArchiveTestPatchRequestBody = `{
            "keys": [
                1
            ],
            "status_field": "status"
        }`
    
    // Fuzz strategies
    const skyrampArchiveTestPatchFuzzedBody = {
        "keys": [-10],
        "status_field": "0123456789"
    };
    // Fuzz status codes
    const expectedSkyrampArchiveTestPatchStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };
    // Fuzz status codes for Null values
    const expectedSkyrampArchiveTestPatchNullStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };

    // Execute Request
    let skyrampArchiveTestPatchResponse = await client.sendRequest({
        url:URL,
        path:"/archive/skyramp_archive_test",
        method:"PATCH",
        body:skyrampArchiveTestPatchRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(skyrampArchiveTestPatchFuzzedBody)) {
        // Execute Request
        skyrampArchiveTestPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/skyramp_archive_test",
            method:"PATCH",
            body:skyrampArchiveTestPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(skyrampArchiveTestPatchFuzzedBody, key)},
            expectedCode:getValue(expectedSkyrampArchiveTestPatchStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(skyrampArchiveTestPatchFuzzedBody, key)}`
        });


        // Execute Request
        skyrampArchiveTestPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/skyramp_archive_test",
            method:"PATCH",
            body:skyrampArchiveTestPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedSkyrampArchiveTestPatchNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

