// Generated by Skyramp v1.3.13 on 2026-03-16 22:18:08.340623987 +0000 UTC m=+86.771161504
// Command: skyramp generate contract rest http://localhost:8055/utils/hash/simple \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_utils_hash_simple.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params value=test,length=4 \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/hash/simple GET
test('testSimpleGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient({
        runtime: "docker",
        dockerNetwork: "directus_default",
        dockerSkyrampPort: 35142
    });
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const simpleGetResponse = await client.sendRequest({
        url: URL,
        path: "/utils/hash/simple",
        method: "GET",
        headers: headers,
        queryParams: {
            "length": "4",
            "value": "test"
        }
    });

    // Generated Assertions
    expect(checkStatusCode(simpleGetResponse, "20x"), 'status code').toBeTruthy();
});
