// Generated by Skyramp v1.3.13 on 2026-03-16 18:02:30.458780335 +0000 UTC m=+74.594580289
// Command: skyramp generate contract rest http://localhost:8055/math/add \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_math_add.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params a=3,b=5 \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /math/add GET
test('testAddGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient({
        runtime: "docker",
        dockerNetwork: "directus_default",
        dockerSkyrampPort: 35142
    });
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const addGetResponse = await client.sendRequest({
        url: URL,
        path: "/math/add",
        method: "GET",
        headers: headers,
        queryParams: {
            "a": "3",
            "b": "5"
        }
    });

    // Generated Assertions
    expect(checkStatusCode(addGetResponse, "20x"), 'status code').toBeTruthy();
});
