// Generated by Skyramp v1.3.13 on 2026-03-18 01:38:45.761670495 +0000 UTC m=+170.554277669
// Command: skyramp generate contract rest http://localhost:8055/exports/test_articles \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_export_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/test_articles POST
test('testTestArticlesPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testArticlesPostRequestBody: string = `{
        "format": "json"
    }`;

    // Execute Request
    const testArticlesPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/test_articles",
        method: "POST",
        body: testArticlesPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(testArticlesPostResponse, "20x"), 'status code').toBeTruthy();
});
