// Generated by Skyramp v1.3.13 on 2026-03-17 22:48:13.7800851 +0000 UTC m=+137.846141410
// Command: skyramp generate fuzz rest http://localhost:8055/exports/test_export_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output fuzz_exports_collection.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/test_export_items POST
test('testTestExportItemsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testExportItemsPostRequestBody = `{
            "format": "json"
        }`
    
    // Fuzz strategies
    const testExportItemsPostFuzzedBody = {"format": "0123456789"};
    // Fuzz status codes
    const expectedTestExportItemsPostStatusCode: Record<string, string> = {"format": "40x"};
    // Fuzz status codes for Null values
    const expectedTestExportItemsPostNullStatusCode: Record<string, string> = {"format": "40x"};

    // Execute Request
    let testExportItemsPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/test_export_items",
        method:"POST",
        body:testExportItemsPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(testExportItemsPostFuzzedBody)) {
        // Execute Request
        testExportItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_export_items",
            method:"POST",
            body:testExportItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(testExportItemsPostFuzzedBody, key)},
            expectedCode:getValue(expectedTestExportItemsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(testExportItemsPostFuzzedBody, key)}`
        });


        // Execute Request
        testExportItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_export_items",
            method:"POST",
            body:testExportItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedTestExportItemsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

