// Generated by Skyramp v1.3.13 on 2026-03-16 22:18:08.386241385 +0000 UTC m=+86.816778902
// Command: skyramp generate fuzz rest http://localhost:8055/utils/hash/simple \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output fuzz_utils_hash_simple.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params value=test,length=4 \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /utils/hash/simple GET
test('testSimpleGet', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient({
        runtime:"docker",
        dockerNetwork:"directus_default",
        dockerSkyrampPort:35142
    });

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Fuzz strategies
    const simpleGetFuzzedQuery: Record<string, string|number|boolean|object> = {
        "length": "4",
        "value": "test"
    };
    // Fuzz status codes
    const expectedSimpleGetFuzzedQueryStatusCode: Record<string, string> = {
        "length": "40x",
        "value": "40x"
    };

    // Execute Request
    let simpleGetResponse = await client.sendRequest({
        url:URL,
        path:"/utils/hash/simple",
        method:"GET",
        headers:headers,
        queryParams:{
            "length": "4",
            "value": "test"
        },
        expectedCode:"20x"
    });


    for (const key of iterate(simpleGetFuzzedQuery)) {
        let query_params: Record<string, string> = {
            "length": "4",
            "value": "test"
        };
        query_params[key] = simpleGetFuzzedQuery[key];

        // Execute Request
        simpleGetResponse = await client.sendRequest({
            url:URL,
            path:"/utils/hash/simple",
            method:"GET",
            headers:headers,
            queryParams:query_params,
            expectedCode:expectedSimpleGetFuzzedQueryStatusCode[key],
            description:`Fuzzing query param ${key} to ${simpleGetFuzzedQuery[key]}`
        });


        query_params = {
            "length": "4",
            "value": "test"
        };
        query_params[key] = "";

        // Execute Request
        simpleGetResponse = await client.sendRequest({
            url:URL,
            path:"/utils/hash/simple",
            method:"GET",
            headers:headers,
            queryParams:query_params,
            expectedCode:expectedSimpleGetFuzzedQueryStatusCode[key],
            description:`Fuzzing query param ${key} to ""`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

