// Generated by Skyramp v1.3.13 on 2026-03-18 01:38:48.886161429 +0000 UTC m=+173.678768584
// Command: skyramp generate fuzz rest http://localhost:8055/exports/test_articles \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output fuzz_export_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/test_articles POST
test('testTestArticlesPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testArticlesPostRequestBody = `{
            "format": "json"
        }`
    
    // Fuzz strategies
    const testArticlesPostFuzzedBody = {"format": "0123456789"};
    // Fuzz status codes
    const expectedTestArticlesPostStatusCode: Record<string, string> = {"format": "40x"};
    // Fuzz status codes for Null values
    const expectedTestArticlesPostNullStatusCode: Record<string, string> = {"format": "40x"};

    // Execute Request
    let testArticlesPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/test_articles",
        method:"POST",
        body:testArticlesPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(testArticlesPostFuzzedBody)) {
        // Execute Request
        testArticlesPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_articles",
            method:"POST",
            body:testArticlesPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(testArticlesPostFuzzedBody, key)},
            expectedCode:getValue(expectedTestArticlesPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(testArticlesPostFuzzedBody, key)}`
        });


        // Execute Request
        testArticlesPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_articles",
            method:"POST",
            body:testArticlesPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedTestArticlesPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

