// Generated by Skyramp v1.3.14 on 2026-03-20 18:40:21.309556229 +0000 UTC m=+144.225749408
// Command: skyramp generate contract rest http://localhost:8055/utils/hash/generate \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"string":"backward_compat_test_password"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/hash/generate POST
test('testGeneratePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const generatePostRequestBody: string = `{
        "string": "backward_compat_test_password"
    }`;

    // Execute Request
    const generatePostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/hash/generate",
        method: "POST",
        body: generatePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(generatePostResponse, "20x"), 'status code').toBeTruthy();
});
