# Generated by Skyramp v1.3.14 on 2026-03-20 18:49:34.813983234 +0000 UTC m=+295.262145154
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_batch_revert_object_format.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_batch-revert-object-format.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    users_POST_request_body = r'''{
        "email": "test-revert-1742428800@example.com",
        "first_name": "Revert",
        "last_name": "Test",
        "password": "Test1234!",
        "status": "active"
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    users_users_PATCH_request_body = r'''{
        "first_name": "Reverted"
    }'''
    
    # Execute Request
    users_users_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/users/{users}",
        method="PATCH",
        body=users_users_PATCH_request_body,
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_POST_response, "data.id")}
    )
    # Generated Assertions
    assert users_users_PATCH_response.status_code == 200

    # Execute Request
    revisions_GET_response = client.send_request(
        url=URL_localhost,
        path="/revisions",
        method="GET",
        headers=headers,
        query_params={
            "filter[collection][_eq]": ["directus_users"],
            "limit": ["1"],
            "sort": ["-id"]
        }
    )
    # Generated Assertions
    assert revisions_GET_response.status_code == 200

    # Request Body - chain revision ID from GET /revisions response
    revert_revision_id = skyramp.get_response_value(revisions_GET_response, "data[0].id")
    revert_POST_request_body = '{"revisions": [' + str(revert_revision_id) + ']}'

    # Execute Request
    revert_POST_response = client.send_request(
        url=URL_localhost,
        path="/utils/revert",
        method="POST",
        body=revert_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert revert_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
