// Generated by Skyramp v1.3.14 on 2026-03-20 17:53:55.232381504 +0000 UTC m=+368.018299277
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_sort_security_no_auth.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_sort-security-no-auth.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const directusFilesPostRequestBody = `{
            "item": 1,
            "to": 2
        }`
    
    // Execute Request
    let directusFilesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/sort/directus_files",
        method:"POST",
        body:directusFilesPostRequestBody
    });

    // Generated Assertions
    expect(directusFilesPostResponse.statusCode, 'status code').toBe(401);
});

