# Generated by Skyramp v1.3.14 on 2026-03-20 18:49:20.024744003 +0000 UTC m=+280.472905913
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_batch_revert_auth_boundary.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_batch-revert-auth-boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    revert_POST_request_body = r'''{
        "revisions": [
            1
        ]
    }'''
    
    # Execute Request
    revert_POST_response = client.send_request(
        url=URL_localhost,
        path="/utils/revert",
        method="POST",
        body=revert_POST_request_body
    )
    # Generated Assertions
    assert revert_POST_response.status_code == 403


if __name__ == "__main__":
    test_integration()
