# Generated by Skyramp v1.3.14 on 2026-03-20 18:48:48.618956799 +0000 UTC m=+249.067118729
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_batch-revert-invalid-body.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    revert_POST_request_body = r'''{
        "invalid": "body"
    }'''
    
    # Execute Request
    revert_POST_response = client.send_request(
        url=URL_localhost,
        path="/utils/revert",
        method="POST",
        body=revert_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert revert_POST_response.status_code == 400


if __name__ == "__main__":
    test_integration()
