// Generated by Skyramp v1.3.14 on 2026-03-20 18:25:27.161122049 +0000 UTC m=+312.272133631
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_sort_403_forbidden.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_sort-403-forbidden.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const rolesPostRequestBody = `{
            "admin_access": false,
            "app_access": false,
            "name": "skyramp-no-sort-role"
        }`
    
    // Execute Request
    let rolesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/roles",
        method:"POST",
        body:rolesPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(rolesPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const usersPostRequestBody = `{
            "email": "nosortuser@skyramp.test",
            "password": "Skyramp123!",
            "role": "${getResponseValue(rolesPostResponse, "data.id")}"
        }`
    
    // Execute Request
    let usersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/users",
        method:"POST",
        body:usersPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(usersPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const loginPostRequestBody = `{
            "email": "nosortuser@skyramp.test",
            "password": "Skyramp123!"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/auth/login",
        method:"POST",
        body:loginPostRequestBody
    });

    // Generated Assertions
    expect(loginPostResponse.statusCode, 'status code').toBe(200);

    // Definition of authentication header
    const token_from_loginPost: Record<string, string> = {"Authorization": "Bearer " + getResponseValue(loginPostResponse, "data.access_token")};

    // Request Body
    const directusFilesPostRequestBody = `{
            "item": 1,
            "to": 2
        }`
    
    // Execute Request
    let directusFilesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/sort/directus_files",
        method:"POST",
        body:directusFilesPostRequestBody,
        headers:token_from_loginPost
    });

    // Generated Assertions
    expect(directusFilesPostResponse.statusCode, 'status code').toBe(403);
});

