// Generated by Skyramp v1.3.14 on 2026-03-20 18:40:50.877057436 +0000 UTC m=+173.793250625
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_hash_generate_auth_boundary.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_hash-generate-auth-boundary.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const generatePostRequestBody = `{
            "string": "test_password_auth_check"
        }`
    
    // Execute Request
    let generatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/generate",
        method:"POST",
        body:generatePostRequestBody
    });

    // Generated Assertions
    expect(generatePostResponse.statusCode, 'status code').toBe(401);
});

