// Generated by Skyramp v1.3.14 on 2026-03-20 18:42:11.8945529 +0000 UTC m=+116.619086850
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_ping_liveness_probe_workflow_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_ping-workflow-liveness-probe.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let pingGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/server/ping",
        method:"GET"
    });

    // Generated Assertions
    expect(pingGetResponse.statusCode, 'status code').toBe(200);
});

