// Generated by Skyramp v1.3.14 on 2026-03-20 19:01:13.042302158 +0000 UTC m=+137.347939667
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_hash_generate_missing_fields.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_hash-generate-missing-fields.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const generatePostRequestBody = `{}`
    
    // Execute Request
    let generatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/generate",
        method:"POST",
        body:generatePostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(generatePostResponse.statusCode, 'status code').toBe(400);
});

