# Generated by Skyramp v1.3.14 on 2026-03-20 18:46:26.730748147 +0000 UTC m=+197.388784350
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_head-item-system-collection.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    directus_users_9bc9d1a6_00cb_40ad_a560_307f9b0ec985_HEAD_request_body = r'''{}'''
    
    # Execute Request
    directus_users_9bc9d1a6_00cb_40ad_a560_307f9b0ec985_HEAD_response = client.send_request(
        url=URL_localhost,
        path="/items/directus_users/9bc9d1a6-00cb-40ad-a560-307f9b0ec985",
        method="HEAD",
        body=directus_users_9bc9d1a6_00cb_40ad_a560_307f9b0ec985_HEAD_request_body,
        headers=headers
    )
    # Generated Assertions
    assert directus_users_9bc9d1a6_00cb_40ad_a560_307f9b0ec985_HEAD_response.status_code == 403


if __name__ == "__main__":
    test_integration()
