// Generated by Skyramp v1.3.14 on 2026-03-20 18:25:23.295982236 +0000 UTC m=+308.406993828
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_sort_no_sort_field.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_sort-no-sort-field-validation.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "skyramp_no_sort_field",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true,
                        "interface": "input",
                        "readonly": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                }
            ],
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const sortPostRequestBody = `{
            "item": 1,
            "to": 2
        }`
    
    // Execute Request
    let sortPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/sort/{sort}",
        method:"POST",
        body:sortPostRequestBody,
        headers:headers,
        pathParams:{"sort": getResponseValue(collectionsPostResponse, "data.meta.collection")}
    });

    // Generated Assertions
    expect(sortPostResponse.statusCode, 'status code').toBe(400);
});

