// Generated by Skyramp v1.3.14 on 2026-03-20 18:41:11.13953702 +0000 UTC m=+224.630852306
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_uuid_auth_boundary.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_uuid-auth-boundary.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let uuidGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/random/uuid",
        method:"GET"
    });

    // Generated Assertions
    expect(uuidGetResponse.statusCode, 'status code').toBe(401);
});

