// Generated by Skyramp v1.3.14 on 2026-03-20 17:54:00.340237162 +0000 UTC m=+373.126154935
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_sort_backwards_compat.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_sort-single-backwards-compat.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "skyramp_sort_compat",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true,
                        "interface": "input",
                        "readonly": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "sort_order",
                    "meta": {
                        "hidden": true,
                        "interface": "input"
                    },
                    "schema": {},
                    "type": "integer"
                }
            ],
            "meta": {
                "sort_field": "sort_order"
            },
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "sort_order": 1
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": getResponseValue(collectionsPostResponse, "data.meta.collection")}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPost1RequestBody = `{
            "sort_order": 2
        }`
    
    // Execute Request
    let itemsPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPost1RequestBody,
        headers:headers,
        pathParams:{"items": getResponseValue(collectionsPostResponse, "data.meta.collection")}
    });

    // Generated Assertions
    expect(itemsPost1Response.statusCode, 'status code').toBe(200);

    // Request Body
    const sortPostRequestBody = `{
            "item": ${getResponseValue(itemsPostResponse, "data.id")},
            "to": ${getResponseValue(itemsPost1Response, "data.id")}
        }`
    
    // Execute Request
    let sortPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/sort/{sort}",
        method:"POST",
        body:sortPostRequestBody,
        headers:headers,
        pathParams:{"sort": getResponseValue(collectionsPostResponse, "data.meta.collection")}
    });

    // Generated Assertions
    expect(sortPostResponse.statusCode, 'status code').toBe(200);
});

