// Generated by Skyramp v1.3.13 on 2026-03-18 01:38:25.79283883 +0000 UTC m=+150.585445984
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_export_csv_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_export-csv-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "test_reports";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_reports",
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "title": "Q1 Report",
            "value": 42
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
});

