// Generated by Skyramp v1.3.13 on 2026-03-16 22:18:32.860877336 +0000 UTC m=+111.291414843
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_hash_simple_length_param.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_hash-simple-length-param.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let simpleGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/simple",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(simpleGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let simpleGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/simple",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(simpleGet1Response.statusCode, 'status code').toBe(200);

    // Execute Request
    let simpleGet2Response = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/simple",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(simpleGet2Response.statusCode, 'status code').toBe(200);
});

