// Generated by Skyramp v1.3.13 on 2026-03-16 21:39:17.513939919 +0000 UTC m=+198.009408538
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_ratelimit_middleware_integration.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_login-ratelimit-middleware-flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "admin@example.com",
            "mode": "json",
            "password": "password"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(loginPostResponse.statusCode, 'status code').toBe(200);

    // Definition of authentication header
    const token_from_loginPost: Record<string, string> = {"Authorization": "Bearer " + getResponseValue(loginPostResponse, "data.access_token")};

    // Execute Request
    let meGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/users/me",
        method:"GET",
        headers:token_from_loginPost
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);
});

