// Generated by Skyramp v1.3.13 on 2026-03-16 21:39:17.615289354 +0000 UTC m=+198.110757973
// Command: skyramp generate contract rest http://localhost:8055/auth/login \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output login_ratelimit_contract.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"email":"admin@example.com","password":"password","mode":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /auth/login POST
test('testLoginPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody: string = `{
        "email": "admin@example.com",
        "mode": "json",
        "password": "password"
    }`;

    // Execute Request
    const loginPostResponse = await client.sendRequest({
        url: URL,
        path: "/auth/login",
        method: "POST",
        body: loginPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(loginPostResponse, "20x"), 'status code').toBeTruthy();
});
