// Generated by Skyramp v1.3.13 on 2026-03-16 21:39:17.79885179 +0000 UTC m=+198.294320409
// Command: skyramp generate fuzz rest http://localhost:8055/auth/login \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output login_ratelimit_fuzz.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"email":"admin@example.com","password":"password","mode":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /auth/login POST
test('testLoginPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "admin@example.com",
            "password": "password",
            "mode": "json"
        }`
    
    // Fuzz strategies
    const loginPostFuzzedBody = {
        "email": "0123456789",
        "mode": "0123456789",
        "password": "0123456789"
    };
    // Fuzz status codes
    const expectedLoginPostStatusCode: Record<string, string> = {
        "email": "40x",
        "mode": "40x",
        "password": "40x"
    };
    // Fuzz status codes for Null values
    const expectedLoginPostNullStatusCode: Record<string, string> = {
        "email": "40x",
        "mode": "40x",
        "password": "40x"
    };

    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL,
        path:"/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(loginPostFuzzedBody)) {
        // Execute Request
        loginPostResponse = await client.sendRequest({
            url:URL,
            path:"/auth/login",
            method:"POST",
            body:loginPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(loginPostFuzzedBody, key)},
            expectedCode:getValue(expectedLoginPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(loginPostFuzzedBody, key)}`
        });


        // Execute Request
        loginPostResponse = await client.sendRequest({
            url:URL,
            path:"/auth/login",
            method:"POST",
            body:loginPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedLoginPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

