// Generated by Skyramp v1.3.14 on 2026-03-20 18:45:30.906414834 +0000 UTC m=+225.995431808
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_archived_status_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_notifications-archived-status-verification.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const notificationsPostRequestBody = `{
            "message": "This notification will be marked as archived",
            "recipient": "26d4af7d-4d57-41cf-b0be-e00d9d3d731e",
            "subject": "Skyramp Test Notification"
        }`
    
    // Execute Request
    let notificationsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications",
        method:"POST",
        body:notificationsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(notificationsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const readPatchRequestBody = `{}`
    
    // Execute Request
    let readPatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/read",
        method:"PATCH",
        body:readPatchRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(readPatchResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let notificationsNotificationsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/{notifications}",
        method:"GET",
        headers:headers,
        pathParams:{"notifications": getResponseValue(notificationsPostResponse, "data.id")}
    });

    // Generated Assertions
    expect(notificationsNotificationsGetResponse.statusCode, 'status code').toBe(200);
});

