// Generated by Skyramp v1.3.14 on 2026-03-20 18:45:28.322554893 +0000 UTC m=+223.411571876
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_read_unauthenticated_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_notifications-read-unauthenticated.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const readPatchRequestBody = `{}`
    
    // Execute Request
    let readPatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/read",
        method:"PATCH",
        body:readPatchRequestBody
    });

    // Generated Assertions
    expect(readPatchResponse.statusCode, 'status code').toBe(403);
});

