// Generated by Skyramp v1.3.14 on 2026-03-20 18:41:43.707870072 +0000 UTC m=+88.432403992
// Command: skyramp generate contract rest http://localhost:8055/server/ping \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--response-data {"data":"pong","uptime":42.5} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /server/ping GET
test('testPingGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedPingGetResponseBody: string = `{
        "data": "pong",
        "uptime": 42.5
    }`;

    // Execute Request
    const pingGetResponse = await client.sendRequest({
        url: URL,
        path: "/server/ping",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(pingGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(pingGetResponse, expectedPingGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(pingGetResponse, "data"), 'value').not.toBeNull();
    expect(getResponseValue(pingGetResponse, "uptime"), 'value').not.toBeNull();
});
