// Generated by Skyramp v1.3.14 on 2026-03-20 18:44:37.751225465 +0000 UTC m=+172.840242448
// Command: skyramp generate contract rest http://localhost:8055/notifications/read \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /notifications/read PATCH
test('testReadPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const readPatchResponse = await client.sendRequest({
        url: URL,
        path: "/notifications/read",
        method: "PATCH",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(readPatchResponse, "20x"), 'status code').toBeTruthy();
});
