// Generated by Skyramp v1.3.14 on 2026-03-20 18:49:44.900792676 +0000 UTC m=+219.983857378
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_stats_no_auth.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/scenario_server-stats-no-auth.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let statsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/server/stats",
        method:"GET"
    });

    // Generated Assertions
    expect(statsGetResponse.statusCode, 'status code').toBe(403);
});

