// Generated by Skyramp v1.3.13 on 2026-03-18 04:18:31.57565277 +0000 UTC m=+155.162972940
// Command: skyramp generate fuzz rest http://localhost:8055/exports/skyramp_export_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/skyramp_export_items POST
test('testSkyrampExportItemsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const skyrampExportItemsPostRequestBody = `{
            "format": "json"
        }`
    
    // Fuzz strategies
    const skyrampExportItemsPostFuzzedBody = {"format": "0123456789"};
    // Fuzz status codes
    const expectedSkyrampExportItemsPostStatusCode: Record<string, string> = {"format": "40x"};
    // Fuzz status codes for Null values
    const expectedSkyrampExportItemsPostNullStatusCode: Record<string, string> = {"format": "40x"};

    // Execute Request
    let skyrampExportItemsPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/skyramp_export_items",
        method:"POST",
        body:skyrampExportItemsPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(skyrampExportItemsPostFuzzedBody)) {
        // Execute Request
        skyrampExportItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/skyramp_export_items",
            method:"POST",
            body:skyrampExportItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(skyrampExportItemsPostFuzzedBody, key)},
            expectedCode:getValue(expectedSkyrampExportItemsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(skyrampExportItemsPostFuzzedBody, key)}`
        });


        // Execute Request
        skyrampExportItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/skyramp_export_items",
            method:"POST",
            body:skyrampExportItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedSkyrampExportItemsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

