// Generated by Skyramp v1.3.13 on 2026-03-18 04:18:28.306312875 +0000 UTC m=+151.893633045
// Command: skyramp generate contract rest http://localhost:8055/exports/skyramp_export_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/skyramp_export_items POST
test('testSkyrampExportItemsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const skyrampExportItemsPostRequestBody: string = `{
        "format": "json"
    }`;

    // Execute Request
    const skyrampExportItemsPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/skyramp_export_items",
        method: "POST",
        body: skyrampExportItemsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(skyrampExportItemsPostResponse, "20x"), 'status code').toBeTruthy();
});
