// Generated by Skyramp v1.3.14 on 2026-03-20 18:48:36.246453331 +0000 UTC m=+151.329518031
// Command: skyramp generate contract rest http://localhost:8055/server/stats \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--response-data {"data":{"node_version":"v20.0.0","uptime_seconds":1.234,"memory":{"rss":52428800,"heap_total":33554432,"heap_used":20971520,"external":1048576},"pid":1}} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /server/stats GET
test('testStatsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedStatsGetResponseBody: string = `{
        "data": {
            "memory": {
                "external": 1048576,
                "heap_total": 33554432,
                "heap_used": 20971520,
                "rss": 52428800
            },
            "node_version": "v20.0.0",
            "pid": 1,
            "uptime_seconds": 1.234
        }
    }`;

    // Execute Request
    const statsGetResponse = await client.sendRequest({
        url: URL,
        path: "/server/stats",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(statsGetResponse, "20x"), 'status code').toBeTruthy();
    expect(checkSchema(statsGetResponse, expectedStatsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(statsGetResponse, "data.memory.external"), 'value').not.toBeNull();
    expect(getResponseValue(statsGetResponse, "data.memory.heap_total"), 'value').not.toBeNull();
    expect(getResponseValue(statsGetResponse, "data.memory.heap_used"), 'value').not.toBeNull();
});
