# Generated by Skyramp v1.3.14 on 2026-03-20 18:47:14.924895136 +0000 UTC m=+245.582931329
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_head_item_not_found.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_head-item-not-found.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    articles_3fa85f64_5717_4562_b3fc_2c963f66afa6_HEAD_request_body = r'''{}'''
    
    # Execute Request
    articles_3fa85f64_5717_4562_b3fc_2c963f66afa6_HEAD_response = client.send_request(
        url=URL_localhost,
        path="/items/articles/3fa85f64-5717-4562-b3fc-2c963f66afa6",
        method="HEAD",
        body=articles_3fa85f64_5717_4562_b3fc_2c963f66afa6_HEAD_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_3fa85f64_5717_4562_b3fc_2c963f66afa6_HEAD_response.status_code == 404


if __name__ == "__main__":
    test_integration()
