# Generated by Skyramp v1.3.14 on 2026-03-20 18:47:01.550852221 +0000 UTC m=+232.208888424
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_head_item_exists_lifecycle.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/scenario_head-item-exists-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    collections_POST_request_body = r'''{
        "collection": "test_head_check",
        "fields": [
            {
                "field": "id",
                "meta": {
                    "hidden": true,
                    "interface": "input",
                    "readonly": true
                },
                "schema": {
                    "has_auto_increment": true,
                    "is_primary_key": true
                },
                "type": "integer"
            },
            {
                "field": "title",
                "meta": {
                    "interface": "input"
                },
                "schema": {},
                "type": "string"
            }
        ],
        "meta": {
            "icon": "box"
        },
        "schema": {}
    }'''
    
    # Execute Request
    collections_POST_response = client.send_request(
        url=URL_localhost,
        path="/collections",
        method="POST",
        body=collections_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert collections_POST_response.status_code == 200

    # Request Body
    items_POST_request_body = r'''{
        "title": "Test item for HEAD existence check"
    }'''
    
    # Execute Request
    items_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="POST",
        body=items_POST_request_body,
        headers=headers,
        path_params={"items": skyramp.get_response_value(collections_POST_response, "data.meta.collection")}
    )
    # Generated Assertions
    assert items_POST_response.status_code == 200

    # Request Body
    items_1_HEAD_request_body = r'''{}'''
    
    # Execute Request
    items_1_HEAD_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}/{items_1}",
        method="HEAD",
        body=items_1_HEAD_request_body,
        headers=headers,
        path_params={
            "items": skyramp.get_response_value(collections_POST_response, "data.meta.collection"),
            "items_1": skyramp.get_response_value(items_POST_response, "data.id")
        }
    )
    # Generated Assertions
    assert items_1_HEAD_response.status_code == 204


if __name__ == "__main__":
    test_integration()
