// Generated by Skyramp v1.3.13 on 2026-03-16 21:05:43.124246163 +0000 UTC m=+114.189922798
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output test_exports_json_integration.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_export-json-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "export_test_items";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "export_test_items",
            "meta": {
                "icon": "box",
                "note": "Test collection for export workflow"
            },
            "schema": {
                "name": "export_test_items"
            }
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "status": "published",
            "title": "Sample Export Item"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const exportsPostRequestBody = `{
            "fields": [
                "id",
                "title",
                "status"
            ],
            "format": "json"
        }`
    
    // Execute Request
    let exportsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/exports/{exports}",
        method:"POST",
        body:exportsPostRequestBody,
        headers:headers,
        pathParams:{"exports": items}
    });

    // Generated Assertions
    expect(exportsPostResponse.statusCode, 'status code').toBe(200);
});

