# Generated by Skyramp v1.3.13 on 2026-03-18 04:28:14.129093672 +0000 UTC m=+103.331071690
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_archive_item_integration.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/directus/directus/tests/scenario_archive-item-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    items = "archive_test_items"

    # Request Body
    collections_POST_request_body = r'''{
        "collection": "archive_test_items",
        "fields": [
            {
                "field": "id",
                "meta": {
                    "hidden": true,
                    "readonly": true
                },
                "schema": {
                    "has_auto_increment": true,
                    "is_primary_key": true
                },
                "type": "integer"
            },
            {
                "field": "status",
                "meta": {
                    "width": "full"
                },
                "schema": {
                    "default_value": "published"
                },
                "type": "string"
            },
            {
                "field": "title",
                "meta": {
                    "width": "full"
                },
                "schema": {},
                "type": "string"
            }
        ],
        "meta": {
            "icon": "article"
        }
    }'''
    
    # Execute Request
    collections_POST_response = client.send_request(
        url=URL_localhost,
        path="/collections",
        method="POST",
        body=collections_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert collections_POST_response.status_code == 200

    # Request Body
    items_POST_request_body = r'''{
        "status": "published",
        "title": "Test Article for Archiving"
    }'''
    
    # Execute Request
    items_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="POST",
        body=items_POST_request_body,
        headers=headers,
        path_params={"items": items}
    )
    # Generated Assertions
    assert items_POST_response.status_code == 200

    # Request Body
    _item_id = skyramp.get_response_value(items_POST_response, "data.id")
    archive_PATCH_request_body = f'{{"keys": [{_item_id}], "status_field": "status"}}'
    
    # Execute Request
    archive_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/archive/{archive}",
        method="PATCH",
        body=archive_PATCH_request_body,
        headers=headers,
        path_params={"archive": items}
    )
    # Generated Assertions
    assert archive_PATCH_response.status_code == 200

    # Execute Request
    items_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}/{items_1}",
        method="GET",
        headers=headers,
        path_params={
            "items": items,
            "items_1": skyramp.get_response_value(items_POST_response, "data.id")
        }
    )
    # Generated Assertions
    assert items_1_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
