# Generated by Skyramp v1.3.13 on 2026-03-18 04:28:17.147221392 +0000 UTC m=+106.349199420
# Command: skyramp generate fuzz rest http://localhost:8055/archive/archive_test_items \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_archive_fuzz.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"keys":[1],"status_field":"status"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

# fuzz test for /archive/archive_test_items PATCH
def test_archive_test_items_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    archive_test_items_PATCH_request_body = r'''{
      "keys": [
        1
      ],
      "status_field": "status"
    }'''
    
    # Fuzz strategies
    archive_test_items_patch_fuzzed_body = {
        "keys": [-10],
        "status_field": "0123456789"
    }
    # Fuzz status codes
    expected_archive_test_items_patch_status_code = {
        "keys": ["40x"],
        "status_field": "40x"
    }
    # Fuzz status codes for Null values
    expected_archive_test_items_patch_null_status_code = {
        "keys": ["40x"],
        "status_field": "40x"
    }

    # Execute Request
    archive_test_items_PATCH_response = client.send_request(
        url=URL,
        path="/archive/archive_test_items",
        method="PATCH",
        body=archive_test_items_PATCH_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(archive_test_items_patch_fuzzed_body):
        # Execute Request
        archive_test_items_PATCH_response = client.send_request(
            url=URL,
            path="/archive/archive_test_items",
            method="PATCH",
            body=archive_test_items_PATCH_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(archive_test_items_patch_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_archive_test_items_patch_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(archive_test_items_patch_fuzzed_body, key) }'
        )

        # Execute Request
        archive_test_items_PATCH_response = client.send_request(
            url=URL,
            path="/archive/archive_test_items",
            method="PATCH",
            body=archive_test_items_PATCH_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_archive_test_items_patch_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_archive_test_items_patch()
