// Generated by Skyramp v1.3.13 on 2026-03-17 23:04:01.301500859 +0000 UTC m=+142.706803335
// Command: skyramp generate fuzz rest http://localhost:8055/archive/archive_test_items_1773 \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output test_archive_fuzz.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /archive/archive_test_items_1773 PATCH
test('testArchiveTestItems1773Patch', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archiveTestItems1773PatchRequestBody = `{
            "keys": [
                1
            ],
            "status_field": "status"
        }`
    
    // Fuzz strategies
    const archiveTestItems1773PatchFuzzedBody = {
        "keys": [-10],
        "status_field": "0123456789"
    };
    // Fuzz status codes
    const expectedArchiveTestItems1773PatchStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };
    // Fuzz status codes for Null values
    const expectedArchiveTestItems1773PatchNullStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };

    // Execute Request
    let archiveTestItems1773PatchResponse = await client.sendRequest({
        url:URL,
        path:"/archive/archive_test_items_1773",
        method:"PATCH",
        body:archiveTestItems1773PatchRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(archiveTestItems1773PatchFuzzedBody)) {
        // Execute Request
        archiveTestItems1773PatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/archive_test_items_1773",
            method:"PATCH",
            body:archiveTestItems1773PatchRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(archiveTestItems1773PatchFuzzedBody, key)},
            expectedCode:getValue(expectedArchiveTestItems1773PatchStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(archiveTestItems1773PatchFuzzedBody, key)}`
        });


        // Execute Request
        archiveTestItems1773PatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/archive_test_items_1773",
            method:"PATCH",
            body:archiveTestItems1773PatchRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedArchiveTestItems1773PatchNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

