// Generated by Skyramp v1.3.13 on 2026-03-17 23:03:57.214840713 +0000 UTC m=+138.620143182
// Command: skyramp generate contract rest http://localhost:8055/archive/archive_test_items_1773 \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output test_archive_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/archive_test_items_1773 PATCH
test('testArchiveTestItems1773Patch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archiveTestItems1773PatchRequestBody: string = `{
        "keys": [
            1
        ],
        "status_field": "status"
    }`;

    // Execute Request
    const archiveTestItems1773PatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/archive_test_items_1773",
        method: "PATCH",
        body: archiveTestItems1773PatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(archiveTestItems1773PatchResponse, "20x"), 'status code').toBeTruthy();
});
