# Generated by Skyramp v1.3.13 on 2026-03-17 23:30:15.41957905 +0000 UTC m=+153.793496132
# Command: skyramp generate fuzz rest http://localhost:8055/exports/test_products \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_export_fuzz.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"format":"json","fields":["id","name"],"query":{}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

# fuzz test for /exports/test_products POST
def test_test_products_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    test_products_POST_request_body = r'''{
      "format": "json",
      "fields": [
        "id",
        "name"
      ],
      "query": {}
    }'''
    
    # Fuzz strategies
    test_products_post_fuzzed_body = {
        "fields": [
            "0123456789",
                "0123456789"
        ],
        "format": "0123456789",
        "query": {}
    }
    # Fuzz status codes
    expected_test_products_post_status_code = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x",
        "query": "40x"
    }
    # Fuzz status codes for Null values
    expected_test_products_post_null_status_code = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x",
        "query": "40x"
    }

    # Execute Request
    test_products_POST_response = client.send_request(
        url=URL,
        path="/exports/test_products",
        method="POST",
        body=test_products_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(test_products_post_fuzzed_body):
        # Execute Request
        test_products_POST_response = client.send_request(
            url=URL,
            path="/exports/test_products",
            method="POST",
            body=test_products_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(test_products_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_test_products_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(test_products_post_fuzzed_body, key) }'
        )

        # Execute Request
        test_products_POST_response = client.send_request(
            url=URL,
            path="/exports/test_products",
            method="POST",
            body=test_products_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_test_products_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_test_products_post()
