// Generated by Skyramp v1.3.13 on 2026-03-16 21:06:10.813312623 +0000 UTC m=+141.878989268
// Command: skyramp generate fuzz rest http://localhost:8055/exports/export_test_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output test_exports_fuzz.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json","fields":["id","title","status"],"query":{}} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/export_test_items POST
test('testExportTestItemsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const exportTestItemsPostRequestBody = `{
            "format": "json",
            "fields": [
                "id",
                "title",
                "status"
            ],
            "query": {}
        }`
    
    // Fuzz strategies
    const exportTestItemsPostFuzzedBody = {
        "fields": [
            "0123456789",
                "0123456789",
                "0123456789"
        ],
        "format": "0123456789",
        "query": {}
    };
    // Fuzz status codes
    const expectedExportTestItemsPostStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x",
                "40x"
        ],
        "format": "40x",
        "query": "40x"
    };
    // Fuzz status codes for Null values
    const expectedExportTestItemsPostNullStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x",
                "40x"
        ],
        "format": "40x",
        "query": "40x"
    };

    // Execute Request
    let exportTestItemsPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/export_test_items",
        method:"POST",
        body:exportTestItemsPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(exportTestItemsPostFuzzedBody)) {
        // Execute Request
        exportTestItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/export_test_items",
            method:"POST",
            body:exportTestItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(exportTestItemsPostFuzzedBody, key)},
            expectedCode:getValue(expectedExportTestItemsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(exportTestItemsPostFuzzedBody, key)}`
        });


        // Execute Request
        exportTestItemsPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/export_test_items",
            method:"POST",
            body:exportTestItemsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedExportTestItemsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

