// Generated by Skyramp v1.3.13 on 2026-03-16 21:06:10.715387003 +0000 UTC m=+141.781063647
// Command: skyramp generate contract rest http://localhost:8055/exports/export_test_items \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output test_exports_contract.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json","fields":["id","title","status"]} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/export_test_items POST
test('testExportTestItemsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const exportTestItemsPostRequestBody: string = `{
        "fields": [
            "id",
            "title",
            "status"
        ],
        "format": "json"
    }`;

    // Execute Request
    const exportTestItemsPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/export_test_items",
        method: "POST",
        body: exportTestItemsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(exportTestItemsPostResponse, "20x"), 'status code').toBeTruthy();
});
