// Generated by Skyramp v1.3.13 on 2026-03-18 00:20:29.52665433 +0000 UTC m=+99.142463308
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output test_export_json_flow.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_export-json-flow-20260318.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_export_items",
            "fields": [
                {
                    "field": "name",
                    "meta": {
                        "interface": "input"
                    },
                    "schema": {},
                    "type": "string"
                }
            ],
            "meta": {
                "hidden": false
            },
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Sample Export Item"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": getResponseValue(collectionsPostResponse, "data.schema.name")}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const exportsPostRequestBody = `{
            "format": "json"
        }`
    
    // Execute Request
    let exportsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/exports/{exports}",
        method:"POST",
        body:exportsPostRequestBody,
        headers:headers,
        pathParams:{"exports": getResponseValue(collectionsPostResponse, "data.schema.name")}
    });

    // Generated Assertions
    expect(exportsPostResponse.statusCode, 'status code').toBe(200);
});

