// Generated by Skyramp v1.3.13 on 2026-03-17 23:03:54.677422809 +0000 UTC m=+136.082725274
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output test_archive_item_workflow.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_archive-item-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "archive_test_items_1773";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "archive_test_items_1773",
            "meta": {
                "icon": "box"
            },
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Test Item for Archiving"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);

    // Chain item ID from creation response
    let itemId = getValue(itemsPostResponse, "data.id");

    // Request Body
    const archivePatchRequestBody = `{
            "keys": [
                ${itemId}
            ],
            "status_field": "status"
        }`
    
    // Execute Request
    let archivePatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/archive/{archive}",
        method:"PATCH",
        body:archivePatchRequestBody,
        headers:headers,
        pathParams:{"archive": items}
    });

    // Generated Assertions
    expect(archivePatchResponse.statusCode, 'status code').toBe(200);
});

