// Generated by Skyramp v1.3.13 on 2026-03-17 23:53:46.19923938 +0000 UTC m=+128.339730758
// Command: skyramp generate fuzz rest http://localhost:8055/exports/skyramp_export_test \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output test_exports_fuzz.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json","fields":["id","name"],"query":{"limit":10}} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/skyramp_export_test POST
test('testSkyrampExportTestPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const skyrampExportTestPostRequestBody = `{
            "format": "json",
            "fields": [
                "id",
                "name"
            ],
            "query": {
                "limit": 10
            }
        }`
    
    // Fuzz strategies
    const skyrampExportTestPostFuzzedBody = {
        "fields": [
            "0123456789",
                "0123456789"
        ],
        "format": "0123456789",
        "query": {"limit": -10}
    };
    // Fuzz status codes
    const expectedSkyrampExportTestPostStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x",
        "query": {"limit": "40x"}
    };
    // Fuzz status codes for Null values
    const expectedSkyrampExportTestPostNullStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x",
        "query": {"limit": "40x"}
    };

    // Execute Request
    let skyrampExportTestPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/skyramp_export_test",
        method:"POST",
        body:skyrampExportTestPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(skyrampExportTestPostFuzzedBody)) {
        // Execute Request
        skyrampExportTestPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/skyramp_export_test",
            method:"POST",
            body:skyrampExportTestPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(skyrampExportTestPostFuzzedBody, key)},
            expectedCode:getValue(expectedSkyrampExportTestPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(skyrampExportTestPostFuzzedBody, key)}`
        });


        // Execute Request
        skyrampExportTestPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/skyramp_export_test",
            method:"POST",
            body:skyrampExportTestPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedSkyrampExportTestPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

