# Generated by Skyramp v1.3.13 on 2026-03-17 23:29:37.977025077 +0000 UTC m=+116.350942159
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_export_json_workflow.py \
# 		--output-dir /home/runner/work/directus/directus/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/directus/directus/tests/scenario_export-json-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    items = "test_products"

    # Request Body
    collections_POST_request_body = r'''{
        "collection": "test_products",
        "fields": [
            {
                "field": "id",
                "meta": {
                    "hidden": true,
                    "interface": "input"
                },
                "schema": {
                    "has_auto_increment": true,
                    "is_primary_key": true
                },
                "type": "integer"
            },
            {
                "field": "name",
                "meta": {
                    "interface": "input"
                },
                "schema": {},
                "type": "string"
            }
        ],
        "schema": {
            "name": "test_products"
        }
    }'''
    
    # Execute Request
    collections_POST_response = client.send_request(
        url=URL_localhost,
        path="/collections",
        method="POST",
        body=collections_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert collections_POST_response.status_code == 200

    # Request Body
    items_POST_request_body = r'''{
        "name": "Sample Product"
    }'''
    
    # Execute Request
    items_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="POST",
        body=items_POST_request_body,
        headers=headers,
        path_params={"items": items}
    )
    # Generated Assertions
    assert items_POST_response.status_code == 200

    # Request Body
    exports_POST_request_body = r'''{
        "format": "json"
    }'''
    
    # Execute Request
    exports_POST_response = client.send_request(
        url=URL_localhost,
        path="/exports/{exports}",
        method="POST",
        body=exports_POST_request_body,
        headers=headers,
        path_params={"exports": items}
    )
    # Generated Assertions
    assert exports_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
