// Generated by Skyramp v1.3.19 on 2026-04-18 02:14:25.770950114 +0000 UTC m=+504.781793983
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output activity_my_activity_no_badge.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/activity_my_activity_no_badge_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(77000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await expect(page.getByRole("button", { name: "face My Activity" })).toContainText("My Activity");
    await page.getByRole("button", { name: "face My Activity" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("root").getByText("Items")).toContainText(/\d+ Items/);
    expect(errors).toHaveLength(0);
});
