# Generated by Skyramp v1.3.23 on 2026-05-08 18:43:07.492559466 +0000 UTC m=+310.395174215
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output archive_items_batch_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/skyramp/scenario_archive-items-batch-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    items = "test_archive_items"
    items_1 = "1"

    # Request Body
    collections_POST_request_body = r'''{
        "collection": "test_archive_items",
        "fields": [
            {
                "field": "id",
                "meta": {
                    "hidden": true
                },
                "schema": {
                    "has_auto_increment": true,
                    "is_primary_key": true
                },
                "type": "integer"
            },
            {
                "field": "status",
                "meta": {},
                "schema": {},
                "type": "string"
            }
        ],
        "meta": {},
        "schema": {}
    }'''
    
    # Execute Request
    collections_POST_response = client.send_request(
        url=URL_localhost,
        path="/collections",
        method="POST",
        body=collections_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert collections_POST_response.status_code == 200
    assert skyramp.get_response_value(collections_POST_response, "data.collection") == "test_archive_items"

    # Request Body
    items_POST_request_body = r'''{
        "status": "draft"
    }'''
    
    # Execute Request
    items_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="POST",
        body=items_POST_request_body,
        headers=headers,
        path_params={"items": items}
    )
    # Generated Assertions
    assert items_POST_response.status_code == 200
    assert skyramp.get_response_value(items_POST_response, "data.status") == "draft"
    assert skyramp.get_response_value(items_POST_response, "data.id") is not None
    assert skyramp.get_response_value(items_POST_response, "data.id") > 0

    # Request Body
    archive_PATCH_request_body = r'''{
        "keys": [
            1
        ],
        "status_field": "status"
    }'''
    
    # Execute Request
    archive_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/archive/{archive}",
        method="PATCH",
        body=archive_PATCH_request_body,
        headers=headers,
        path_params={"archive": items}
    )
    # Generated Assertions
    assert archive_PATCH_response.status_code == 200
    assert skyramp.get_response_value(archive_PATCH_response, "data.status_field") == "status"
    assert skyramp.get_response_value(archive_PATCH_response, "data.archived") == 1
    assert skyramp.get_response_value(archive_PATCH_response, "data.keys.0") == skyramp.get_response_value(items_POST_response, "data.id")
    assert skyramp.get_response_value(archive_PATCH_response, "data.keys.1") is None

    # Execute Request
    items_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}/{items_1}",
        method="GET",
        headers=headers,
        path_params={
            "items": items,
            "items_1": items_1
        }
    )
    # Generated Assertions
    assert items_1_GET_response.status_code == 200
    assert skyramp.get_response_value(items_1_GET_response, "data.status") == "archived"
    assert skyramp.get_response_value(items_1_GET_response, "data.id") == skyramp.get_response_value(items_POST_response, "data.id")


if __name__ == "__main__":
    test_integration()
