# Generated by Skyramp v1.3.23 on 2026-05-08 18:43:00.465361537 +0000 UTC m=+303.367976276
# Command: skyramp generate contract rest http://localhost:8055/archive/directus_users \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output archive_system_collection_contract_test.py \
# 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"keys":[1]} \
# 		--response-status-code 403 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

# contract test for /archive/directus_users PATCH
def test_directus_users_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    directus_users_PATCH_request_body = r'''{
        "keys": [
            1
        ]
    }'''

    # Execute Request
    directus_users_PATCH_response = client.send_request(
        url=URL,
        path="/archive/directus_users",
        method="PATCH",
        body=directus_users_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert directus_users_PATCH_response.status_code == 403
    assert skyramp.get_response_value(directus_users_PATCH_response, "errors.0.extensions.code") == "FORBIDDEN"
    assert skyramp.get_response_value(directus_users_PATCH_response, "errors.1") is None


if __name__ == "__main__":
    test_directus_users_patch()
