# Generated by Skyramp v1.3.23 on 2026-05-08 18:43:09.682535559 +0000 UTC m=+312.585150308
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output archive_items_empty_keys_validation_integration_test.py \
# 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/directus/directus/tests/skyramp/scenario_archive-items-empty-keys-validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8055")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    archive = "test_archive_validation"

    # Request Body
    collections_POST_request_body = r'''{
        "collection": "test_archive_validation",
        "fields": [
            {
                "field": "id",
                "meta": {
                    "hidden": true
                },
                "schema": {
                    "has_auto_increment": true,
                    "is_primary_key": true
                },
                "type": "integer"
            },
            {
                "field": "status",
                "meta": {},
                "schema": {},
                "type": "string"
            }
        ],
        "meta": {},
        "schema": {}
    }'''
    
    # Execute Request
    collections_POST_response = client.send_request(
        url=URL_localhost,
        path="/collections",
        method="POST",
        body=collections_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert collections_POST_response.status_code == 200
    assert skyramp.get_response_value(collections_POST_response, "data.collection") == "test_archive_validation"

    # Request Body
    archive_PATCH_request_body = r'''{
        "keys": []
    }'''
    
    # Execute Request
    archive_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/archive/{archive}",
        method="PATCH",
        body=archive_PATCH_request_body,
        headers=headers,
        path_params={"archive": archive}
    )
    # Generated Assertions
    assert archive_PATCH_response.status_code == 400
    assert skyramp.get_response_value(archive_PATCH_response, "errors.0.message") == "Invalid payload. 'keys' must be a non-empty array of primary keys.."
    assert skyramp.get_response_value(archive_PATCH_response, "errors.0.extensions.code") == "INVALID_PAYLOAD"
    assert skyramp.get_response_value(archive_PATCH_response, "errors.1") is None


if __name__ == "__main__":
    test_integration()
