// Generated by Skyramp v1.3.16 on 2026-03-30 07:52:28.711733637 +0000 UTC m=+115.379451890
// Command: skyramp generate contract rest http://localhost:8055/archive/{collection} \
// 		--auth-type Bearer \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output contract_patch_archive_collection.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--path-params collection=articles \
// 		--provider \
// 		--request-data {"keys":["1","2"],"status_field":"status"} \
// 		--response-data {"data":{"archived":2,"keys":["1","2"],"status_field":"status"}} \
// 		--runtime docker

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/{collection} PATCH
test('testArchiveCollectionPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient({
        runtime: "docker",
        dockerNetwork: "directus_default",
        dockerSkyrampPort: 35142
    });
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const collection = "articles";

    // Request Body
    const archiveCollectionPatchRequestBody: string = `{
        "keys": [
            "1",
            "2"
        ],
        "status_field": "status"
    }`;

    // Expected Response Body
    const expectedArchiveCollectionPatchResponseBody: string = `{
        "data": {
            "archived": 2,
            "keys": [
                "1",
                "2"
            ],
            "status_field": "status"
        }
    }`;

    // Execute Request
    const archiveCollectionPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/{collection}",
        method: "PATCH",
        body: archiveCollectionPatchRequestBody,
        headers: headers,
        pathParams: {"collection": collection}
    });

    // Generated Assertions
    expect(checkStatusCode(archiveCollectionPatchResponse, "20x"), 'status code').toBeTruthy();
    expect(checkSchema(archiveCollectionPatchResponse, expectedArchiveCollectionPatchResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(archiveCollectionPatchResponse, "data.archived"), 'value').not.toBeNull();
    expect(getResponseValue(archiveCollectionPatchResponse, "data.keys.0"), 'value').not.toBeNull();
    expect(getResponseValue(archiveCollectionPatchResponse, "data.keys.1"), 'value').not.toBeNull();
    expect(getResponseValue(archiveCollectionPatchResponse, "data.archived"), 'archived count').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(archiveCollectionPatchResponse, "data.archived"), 'archived count matches keys').toBe(2);
    expect(getResponseValue(archiveCollectionPatchResponse, "data.status_field"), 'status_field echo-back').toBe("status");
});
