// Generated by Skyramp v1.3.14 on 2026-03-24 21:51:08.057845139 +0000 UTC m=+137.530417328
// Command: skyramp generate contract rest http://localhost:8055/items/directus_users/count \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_items_system_collection_count_blocked.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 403 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /items/directus_users/count GET
test('testCountGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const countGetResponse = await client.sendRequest({
        url: URL,
        path: "/items/directus_users/count",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(countGetResponse.statusCode, 'status code').toBe(403);
});
