// Generated by Skyramp v1.3.14 on 2026-03-24 21:51:05.936850488 +0000 UTC m=+135.409422667
// Command: skyramp generate contract rest http://localhost:8055/auth/token/info \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_auth_token_info_unauthenticated.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /auth/token/info GET
test('testInfoGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const infoGetResponse = await client.sendRequest({
        url: URL,
        path: "/auth/token/info",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(infoGetResponse.statusCode, 'status code').toBe(400);
});
