// Generated by Skyramp v1.3.23 on 2026-05-08 18:26:53.818802989 +0000 UTC m=+489.429408150
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output exports_invalid_format_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/skyramp/scenario_exports-invalid-format.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let exports = "test_export_fmt";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_export_fmt",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                }
            ]
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection")).toBe("test_export_fmt");

    // Request Body
    const exportsPostRequestBody = `{
            "format": "xml"
        }`
    
    // Execute Request
    let exportsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/exports/{exports}",
        method:"POST",
        body:exportsPostRequestBody,
        headers:headers,
        pathParams:{"exports": exports}
    });

    // Generated Assertions
    expect(exportsPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(exportsPostResponse, "errors.0.message")).toBe("Invalid payload.");
    expect(getValue(exportsPostResponse, "errors.0.extensions.code")).toBe("INVALID_PAYLOAD");
    expect(getValue(exportsPostResponse, "errors.0.extensions.reason")).toBe("format must be 'json' or 'csv'");
    expect(getValue(exportsPostResponse, "errors.1")).toBeUndefined();
});

