// Generated by Skyramp v1.3.23 on 2026-05-08 18:26:51.691227725 +0000 UTC m=+487.301832886
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output export_collection_json_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/skyramp/scenario_export-collection-json.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "test_export_json";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_export_json",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "title",
                    "meta": {},
                    "schema": {},
                    "type": "string"
                }
            ]
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection")).toBe("test_export_json");

    // Request Body
    const itemsPostRequestBody = `{
            "title": "Export Test Item"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, "data.title")).toBe("Export Test Item");
    expect(getValue(itemsPostResponse, "data.id")).toBeGreaterThan(0);

    // Request Body
    const exportsPostRequestBody = `{
            "format": "json"
        }`
    
    // Execute Request
    let exportsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/exports/{exports}",
        method:"POST",
        body:exportsPostRequestBody,
        headers:headers,
        pathParams:{"exports": items}
    });

    // Generated Assertions
    expect(exportsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(exportsPostResponse, "data").length).toBe(1);
    expect(getValue(exportsPostResponse, "data.0.title")).toBe("Export Test Item");
    expect(getValue(exportsPostResponse, "data.0.id")).toBe(getValue(itemsPostResponse, "data.id"));
    expect(getValue(exportsPostResponse, "data.1")).toBeUndefined();
});

