// Generated by Skyramp v1.3.16 on 2026-03-30 07:37:55.949782677 +0000 UTC m=+126.138041708
// Command: skyramp generate contract rest http://localhost:8055/exports/{collection} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/{collection} POST
test('testExportsCollectionPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const collection = "articles";

    // Request Body
    const exportsCollectionPostRequestBody: string = `{
        "format": "json"
    }`;

    // Execute Request
    const exportsCollectionPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/{collection}",
        method: "POST",
        body: exportsCollectionPostRequestBody,
        headers: headers,
        pathParams: {"collection": collection}
    });

    // Generated Assertions
    expect(checkStatusCode(exportsCollectionPostResponse, "20x"), 'status code').toBeTruthy();
    expect(getValue(exportsCollectionPostResponse, "data"), 'data').not.toBeNull();
});
