// Generated by Skyramp v1.3.23 on 2026-05-08 18:25:57.249642779 +0000 UTC m=+432.860247950
// Command: skyramp generate contract rest http://localhost:8055/exports/directus_users \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output exports_system_collection_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--response-status-code 403 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/directus_users POST
test('testDirectusUsersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const directusUsersPostRequestBody: string = `{
        "format": "json"
    }`;

    // Execute Request
    const directusUsersPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/directus_users",
        method: "POST",
        body: directusUsersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusUsersPostResponse.statusCode, 'status code').toBe(403);
    expect(getValue(directusUsersPostResponse, "errors.0.message")).toBe("You don't have permission to access this.");
    expect(getValue(directusUsersPostResponse, "errors.0.extensions.code")).toBe("FORBIDDEN");
    expect(getValue(directusUsersPostResponse, "errors.1")).toBeNull();
});
