// Generated by Skyramp v1.3.14 on 2026-03-24 21:51:39.511519448 +0000 UTC m=+168.984091637
// Command: skyramp generate integration rest \
// 		--auth-header Authorization \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_user_sessions_list.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/skyramp/scenario_user-sessions-list.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let sessionsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/users/me/sessions",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(sessionsGetResponse.statusCode, 'status code').toBe(200);
});

