// Generated by Skyramp v1.3.23 on 2026-05-06 17:58:58.786620427 +0000 UTC m=+449.082605836
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_center_unread_state.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_center_unread_state_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(79000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto("http://localhost:8055/admin/notifications");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    await page.getByRole("textbox", { name: "Password" }).press("Enter");
    await page.getByRole("button", { name: "Remind Later" }).click();
    await expect(page.getByRole("button", { name: /^circle_notifications/ }).first()).toContainText("Test Notification 3");
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(/\/notifications/);
    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Notifications (3)");
    await expect(page.getByRole("button", { name: /^circle_notifications/ })).toHaveCount(3);
    await expect(page.getByRole("button", { name: /^circle_notifications/ }).nth(1)).toContainText("Test Notification 2");
    await expect(page.getByRole("button", { name: "done_all" })).not.toBeDisabled();
    expect(pageErrors).toHaveLength(0);
});
