// Generated by Skyramp v1.3.23 on 2026-05-06 17:58:57.688440482 +0000 UTC m=+447.984425911
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_center_empty_state.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_center_empty_state_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(155000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto("http://localhost:8055/admin");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    await page.getByRole("textbox", { name: "Password" }).press("Enter");
    const response0 = await responsePromise0;
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/notifications");
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(/\/notifications/);
    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Notifications");
    await expect(page.getByRole("paragraph")).toHaveText("No notifications");
    await expect(page.getByRole("button", { name: "done_all" })).toBeDisabled();
    expect(response0.status()).toBe(200);
    expect(pageErrors).toHaveLength(0);
});
