// Generated by Skyramp v1.3.19 on 2026-04-17 19:51:37.124570863 +0000 UTC m=+614.177810954
// Command: skyramp generate contract rest http://localhost:8055/server/info \
// 		--api-schema /home/runner/work/directus/directus/packages/specs/src/openapi.yaml \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output server_info_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /server/info GET
test('testInfoGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedInfoGetResponseBody: string = `{
        "data": {}
    }`;

    // Execute Request
    const infoGetResponse = await client.sendRequest({
        url: URL,
        path: "/server/info",
        method: "GET",
        headers: headers,
        queryParams: {"super_admin_token": null}
    });

    // Generated Assertions
    expect(infoGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(infoGetResponse, expectedInfoGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(infoGetResponse, "data"), 'value').not.toBeNull();
    expect(getResponseValue(infoGetResponse, "data.project"), 'project').not.toBeNull();
    expect(getResponseValue(infoGetResponse, "data.version"), 'version').not.toBeNull();
});
