// Generated by Skyramp v1.3.19 on 2026-04-17 19:51:33.15496078 +0000 UTC m=+610.208200871
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/server_info_ui_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(91000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8055/admin");
    await page.waitForLoadState('networkidle');

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/server-info");
    await page.waitForLoadState('networkidle');

    const headingText = await page.evaluate(() => {
        const h1 = document.querySelector('h1');
        return h1?.textContent?.trim() ?? '';
    });
    if (!headingText.includes('Server Info')) {
        throw new Error(`Expected 'Server Info' heading, got: "${headingText}"`);
    }

    const versionText = await page.evaluate(() => {
        const dds = document.querySelectorAll('dd');
        return dds[0]?.textContent?.trim() ?? '';
    });
    if (versionText === '—') {
        throw new Error('Bug: Version field shows "—" — serverInfo.directus?.version is undefined; API response field names do not match component expectations');
    }

    expect(errors).toHaveLength(0);
});
