// Generated by Skyramp v1.3.19 on 2026-04-17 19:51:49.66627567 +0000 UTC m=+626.719515751
// Command: skyramp generate contract rest http://localhost:8055/server/health \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output server_health_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /server/health GET
test('testHealthGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const healthGetResponse = await client.sendRequest({
        url: URL,
        path: "/server/health",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(healthGetResponse, "20x"), 'status code').toBeTruthy();
    expect(getResponseValue(healthGetResponse, "status"), 'status').toBe("ok");
});
