// Generated by Skyramp v1.3.19 on 2026-04-18 17:15:56.809706014 +0000 UTC m=+681.510525948
// Command: skyramp generate contract rest http://localhost:8055/users/me/sessions \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output sessions_api_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /users/me/sessions GET
test('testSessionsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const sessionsGetResponse = await client.sendRequest({
        url: URL,
        path: "/users/me/sessions",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(sessionsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sessionsGetResponse, "data"), 'data exists').toBeDefined();
    expect(getResponseValue(sessionsGetResponse, "data.0.id"), 'first session id').toBeDefined();
    expect(getResponseValue(sessionsGetResponse, "data.0.expires"), 'first session expires').toBeDefined();
    expect(getResponseValue(sessionsGetResponse, "data.0.ip"), 'first session ip').toBeDefined();
});
