// Generated by Skyramp v1.3.19 on 2026-04-18 02:31:38.920876647 +0000 UTC m=+527.719237748
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sessions_sidebar.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/sessions_sidebar_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(91000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/content");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    await page.getByRole("textbox", { name: "Password" }).press("Enter");
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/sessions");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: /Active Sessions/ })).toContainText("Active Sessions");
    // Expected: sessions list loads with active sessions — FAILS because GET /users/me/sessions returns 500 (s.expires.toISOString is not a function)
    await expect(page.getByText("No active sessions")).not.toBeVisible();
});
