// Generated by Skyramp v1.3.19 on 2026-04-18 17:15:55.911303678 +0000 UTC m=+680.612123612
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sessions_refresh_consistent.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/sessions_refresh_consistent_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(187000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    await page.getByRole("textbox", { name: "Password" }).press("Enter");
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/sessions");
    await page.waitForTimeout(3000);
    await expect(page.getByRole("heading", { name: /Active Sessions/ })).toContainText("Active Sessions");
    await page.getByRole("button", { name: "refresh" }).click();
    await page.waitForTimeout(1500);
    await expect(page.getByRole("heading", { name: /Active Sessions/ })).toContainText("Active Sessions");
    await expect(page.getByText("Mozilla/5.0").first()).toContainText("Mozilla/5.0");
});
