// Generated by Skyramp v1.3.19 on 2026-04-22 01:01:44.806180268 +0000 UTC m=+357.524298932
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output settings_schema_navigation.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/settings_schema_navigation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(234000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/settings/schema");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    // Assert: /settings/schema should render the schema management page, NOT "Page Not Found"
    // This assertion FAILS due to bug: route path 'data-model' in index.ts was never renamed to 'schema'
    await expect(page).toHaveURL(/settings\/schema/);
    await expect(page.getByRole("banner")).not.toContainText("Page Not Found");

    await page.goto("http://localhost:8055/admin/settings/data-model");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    // Assert: redirect from /settings/data-model to /settings/schema should succeed and page should render
    await expect(page).toHaveURL(/settings\/schema/);
    await expect(page.getByRole("banner")).not.toContainText("Page Not Found");

    await page.getByRole("link", { name: "database Data Model" }).click();
    await page.waitForTimeout(1000);
    // Assert: clicking sidebar "Data Model" link should navigate to /settings/schema and render page
    await expect(page).toHaveURL(/settings\/schema/);
    await expect(page.getByRole("link", { name: "database Data Model" })).toHaveAttribute("href", /settings\/schema/);
});
