// Generated by Skyramp v1.3.19 on 2026-04-22 01:05:05.739532949 +0000 UTC m=+558.457651621
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output settings_module_navigation.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/settings_module_navigation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(77000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/content");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.getByRole("link", { name: "settings" }).click();
    await page.waitForTimeout(2000);
    // Assert: clicking Settings module icon should redirect to /settings/schema (via default redirect) and render schema page
    // This FAILS because the route path 'data-model' was never renamed to 'schema' in index.ts
    await expect(page).toHaveURL(/settings\/schema/);
    await expect(page.getByRole("banner")).not.toContainText("Page Not Found");
    // Assert: Data Model sidebar link should point to the new /settings/schema URL
    await expect(page.getByRole("link", { name: "database Data Model" })).toHaveAttribute("href", /settings\/schema/);
});
