// Generated by Skyramp v1.3.19 on 2026-04-22 01:03:47.76538325 +0000 UTC m=+480.483501933
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output settings_redirect_queryparams.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/settings_redirect_queryparams_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/settings");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    // Assert: after login with redirect to /settings, should redirect to /settings/schema and render schema page
    // This FAILS because /settings/schema shows "Page Not Found" (route not registered)
    await expect(page).toHaveURL(/settings\/schema/);
    await expect(page.getByRole("banner")).not.toContainText("Page Not Found");

    await page.goto("http://localhost:8055/admin/settings/data-model?tab=system&search=test");
    await page.waitForTimeout(2000);
    // Assert: query params MUST be preserved in redirect from /settings/data-model to /settings/schema
    // This FAILS because the navigation guard drops query params (returns string '/settings/schema', not {path, query})
    await expect(page).toHaveURL(/settings\/schema\?tab=system&search=test/);
    await expect(page.getByRole("banner")).not.toContainText("Page Not Found");
});
