// Generated by Skyramp v1.3.24 on 2026-05-19 18:07:30.885214098 +0000 UTC m=+547.984001031
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_nav_module_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_nav_module_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(188000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/content");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    await page.getByRole("button", { name: "Sign In" }).click();
    await expect(page).toHaveURL(/\/admin\/content/);
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.getByRole("button", { name: "notifications" }).click();
    await expect(page.getByRole("heading", { name: "No Notifications" })).toBeVisible();
    await page.getByRole("button", { exact: true, name: "close" }).click();
    await page.goto("http://localhost:8055/admin/notifications");
    await expect(page).toHaveURL(/\/admin\/notifications/);
    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Notifications");
    await expect(page.getByRole("button", { name: "done_all" })).toBeDisabled();

    expect(errors).toHaveLength(0);
});
