// Generated by Skyramp v1.3.24 on 2026-05-13 00:17:34.981469416 +0000 UTC m=+285.787321991
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_unread_badge.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_unread_badge_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/notifications");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    const responsePromise = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const loginResponse = await responsePromise;
    expect(loginResponse.status()).toBe(200);

    await page.waitForURL("**/admin/notifications**");
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.waitForTimeout(2000);

    await expect(page).toHaveURL(/\/admin\/notifications/);
    await expect(page.getByRole("heading", { name: "Notifications" })).toHaveText("Notifications");
    await expect(page.getByRole("paragraph").filter({ hasText: "No notifications" })).toHaveText("No notifications");
    await expect(page.getByRole("link", { name: "Notifications" })).toHaveText("Notifications");
    expect(errors).toHaveLength(0);
});
