// Generated by Skyramp v1.3.24 on 2026-05-13 00:19:03.352252909 +0000 UTC m=+374.158105494
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_sidebar_panel.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_sidebar_panel_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/content");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    const responsePromise = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const loginResponse = await responsePromise;
    expect(loginResponse.status()).toBe(200);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.waitForTimeout(1500);

    await page.getByRole("button", { name: "notifications" }).click();
    await page.waitForTimeout(1500);

    await expect(page.getByRole("heading", { name: "Notifications", level: 1 })).toHaveText("Notifications");
    await expect(page.getByRole("heading", { name: "No Notifications" })).toHaveText("No Notifications");
    await expect(page.getByRole("button", { name: "inbox Inbox" })).toBeVisible();
    await expect(page.getByRole("button", { name: "archive Archive" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
