// Generated by Skyramp v1.3.25 on 2026-05-27 18:29:05.692357904 +0000 UTC m=+1.045139293
// Command: skyramp generate ui rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_nav_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/_temp/skyramp/server_info_nav_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi_ServerInfoNavigation', async ({ page }) => {
    test.setTimeout(60000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Navigate to content module first
    await page.goto("http://localhost:8055/admin/content");
    await page.waitForTimeout(2000);

    // Verify content page loaded
    await expect(page).toHaveURL(/\/admin\/content/);

    // Navigate to Server Info module
    await page.goto("http://localhost:8055/admin/server-info");
    await page.waitForTimeout(3000);

    // Assert the Server Info module is accessible and URL is correct
    await expect(page).toHaveURL(/\/admin\/server-info/);

    // Assert the Directus module navigation is present (the left sidebar module bar)
    await expect(page.locator('.navigation[id="module-navigation"], [id="module-navigation"], nav').first()).toBeVisible();

    // Assert the Server Info page content is rendered
    await expect(page.locator(".server-info-page")).toBeVisible();

    // Assert the health status chip is present (server is healthy)
    await expect(page.locator(".v-chip.healthy")).toBeVisible();

    // Assert the server info card is rendered with its 3 data rows (first card = server info)
    await expect(page.locator(".v-card").first()).toBeVisible();
    await expect(page.locator(".info-row")).toHaveCount(3);

    // Assert page has no JS errors
    expect(pageErrors).toHaveLength(0);
});
