// Generated by Skyramp v1.3.24 on 2026-05-13 00:33:10.761177648 +0000 UTC m=+1241.070605467
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_grid_navigation.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/server_info_grid_navigation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(665000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/server-info");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    const responsePromise = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const loginResponse = await responsePromise;
    expect(loginResponse.status()).toBe(200);

    await page.getByRole("button", { name: "Remind Later" }).click();

    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Server Info");
    await expect(page.getByRole("term")).toHaveCount(3);
    await expect(page.getByRole("term").nth(0)).toHaveText("Version");
    await expect(page.getByRole("term").nth(1)).toHaveText("Node.js");

    await page.getByRole("link", { name: "Server Info" }).click();

    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Server Info");
    await expect(errors).toHaveLength(0);
});
