// Generated by Skyramp v1.3.24 on 2026-05-19 18:05:07.438310531 +0000 UTC m=+484.912066603
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_health_refresh.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/server_info_health_refresh_trace.zip

// Import of required libraries
import { expect } from '@skyramp/skyramp';
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(747000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/server-info");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/server-info/);
    await expect(page.getByRole("heading", { name: "Server Info" })).toHaveText("Server Info");
    await expect(page.getByRole("term")).toHaveCount(3);
    await expect(page.getByRole("term").nth(0)).toHaveText("Version");
    await expect(page.getByRole("term").nth(1)).toHaveText("Node.js");
    await expect(page.getByRole("term").nth(2)).toHaveText("OS");
    // Documents bug: component uses serverInfo.directus?.version but API returns data.version directly
    await expect(page.getByRole("definition").nth(0)).toHaveText("11.16.1");

    await page.getByRole("button", { name: "refresh" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    await expect(page).toHaveURL(/server-info/);
    await expect(page.getByRole("heading", { name: "Server Info" })).toHaveText("Server Info");
    await expect(page.getByRole("term")).toHaveCount(3);

    expect(errors).toHaveLength(0);
});
