// Generated by Skyramp v1.3.25 on 2026-05-27 18:27:57.912898148 +0000 UTC m=+1.043839492
// Command: skyramp generate ui rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_refresh_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/_temp/skyramp/server_info_refresh_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi_ServerInfoRefresh', async ({ page }) => {
    test.setTimeout(60000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.goto("http://localhost:8055/admin/server-info");
    await page.waitForTimeout(3000);

    // Assert URL navigation is correct
    await expect(page).toHaveURL(/\/admin\/server-info/);

    // Dismiss any overlay dialogs that might intercept clicks (e.g. project owner modal)
    await page.keyboard.press("Escape").catch(() => {});
    await page.waitForTimeout(1000);

    // Wait for the server info card to be visible before clicking refresh (first card is the server info card)
    await expect(page.locator(".v-card").first()).toBeVisible();

    // Click the Refresh button in the actions toolbar (icon-only button with "Refresh" tooltip)
    // The refresh button uses the `refresh` material icon inside a v-button component
    await page.getByRole("button", { name: "refresh" }).click({ force: true });

    // After refresh, wait for data to reload
    await page.waitForTimeout(3000);
    await expect(page.locator(".v-chip.healthy")).toBeVisible();
    await expect(page.locator(".v-card").first()).toBeVisible();
    await expect(page.locator(".info-row")).toHaveCount(3);

    // Assert page has no JS errors
    expect(pageErrors).toHaveLength(0);
});
