// Generated by Skyramp v1.3.24 on 2026-05-19 18:07:58.950195283 +0000 UTC m=+656.423951345
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_sidebar_navigation.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/server_info_sidebar_nav_trace.zip

// Import of required libraries
import { expect } from '@skyramp/skyramp';
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(83000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/content");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    await page.getByRole("button", { name: "Sign In" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    // Documents bug: Server Info module (dns icon) is missing from admin sidebar navigation
    // The module is registered and route works, but nav icon does not appear in sidebar
    await expect(page.getByRole("navigation").getByRole("link", { name: "Server Info" })).toBeVisible();

    await page.goto("http://localhost:8055/admin/server-info");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/server-info/);
    await expect(page.getByRole("heading", { name: "Server Info" })).toHaveText("Server Info");
    await expect(page.getByRole("term")).toHaveCount(3);
    await expect(page.getByRole("term").nth(0)).toHaveText("Version");
    await expect(page.getByRole("term").nth(1)).toHaveText("Node.js");
    await expect(page.getByRole("term").nth(2)).toHaveText("OS");

    expect(errors).toHaveLength(0);
});
