// Generated by Skyramp v1.3.23 on 2026-05-11 18:43:11.054738685 +0000 UTC m=+964.596889073
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_refresh.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/server_info_refresh_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto("http://localhost:8055/admin/login");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Remind Later" }).click();
    await expect(page).toHaveURL(/\/admin\/server-info/);
    await page.getByRole("button", { name: "refresh" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(/\/admin\/server-info/);
    await page.locator('dt').first().waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.locator('dt').first()).toHaveText("Version");
    // Bug: version shows "—" after refresh — serverInfo.directus?.version is the wrong field path
    await expect(page.locator('dd').first()).toHaveText(/\d+\.\d+/);

    expect(errors).toHaveLength(0);
});
