// Generated by Skyramp v1.3.25 on 2026-05-27 18:23:58.939219559 +0000 UTC m=+1.044381708
// Command: skyramp generate ui rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/_temp/skyramp/server_info_load_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.goto("http://localhost:8055/admin/server-info");
    await page.waitForTimeout(3000);

    // Assert Server Info page loaded with correct URL
    await expect(page).toHaveURL(/\/admin\/server-info/);

    // Assert the health status chip is visible and shows the healthy state
    await expect(page.locator(".v-chip.healthy")).toBeVisible();

    // Assert the info card with server details is visible (first card is the server info card)
    await expect(page.locator(".v-card").first()).toBeVisible();

    // Assert the info grid rows exist (Version, Node.js, OS - 3 rows)
    await expect(page.locator(".info-row")).toHaveCount(3);

    // Assert page has no JS errors
    expect(pageErrors).toHaveLength(0);
});
