// Generated by Skyramp v1.3.25 on 2026-05-27 18:36:39.375665212 +0000 UTC m=+0.834441425
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_center_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    await page.goto("http://localhost:8055/admin/notifications");
    await page.waitForLoadState('networkidle');

    // Assert the Notifications Center page rendered its expected content
    const notificationsHeading = page.getByRole('heading', { name: 'Notifications' });
    await notificationsHeading.waitFor({ state: 'visible', timeout: 10000 });
    await expect(notificationsHeading).toBeVisible();

    // Assert the Refresh button is present (always enabled on notifications page)
    const refreshBtn = page.getByRole('button', { name: 'Refresh' });
    await expect(refreshBtn).toBeVisible();

    // Assert the page URL reflects the notifications route
    expect(page.url()).toContain('/notifications');
});
