// Generated by Skyramp v1.3.24 on 2026-05-18 08:45:43.72356718 +0000 UTC m=+325.144795245
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output archive_validate_empty_keys_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_archive-validate-empty-keys.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let archive = "test_archive_validate";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_archive_validate",
            "fields": [
                {
                    "field": "id",
                    "meta": {},
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "status",
                    "meta": {},
                    "schema": {
                        "default_value": "draft"
                    },
                    "type": "string"
                }
            ],
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection")).toBe("test_archive_validate");

    // Request Body
    const archivePatchRequestBody = `{
            "keys": []
        }`
    
    // Execute Request
    let archivePatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/archive/{archive}",
        method:"PATCH",
        body:archivePatchRequestBody,
        headers:headers,
        pathParams:{"archive": archive}
    });

    // Generated Assertions
    expect(archivePatchResponse.statusCode, 'status code').toBe(400);
    expect(getValue(archivePatchResponse, "errors.0.message")).toBe("Invalid payload. 'keys' must be a non-empty array of primary keys..");
    expect(getValue(archivePatchResponse, "errors.0.extensions.code")).toBe("INVALID_PAYLOAD");
    expect(getValue(archivePatchResponse, "errors.1")).toBeNull();
});

