// Generated by Skyramp v1.3.24 on 2026-05-18 08:45:42.523360217 +0000 UTC m=+323.944588292
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output archive_items_collection_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_archive-items-collection.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "test_archive_items";
    let items_1 = "1";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_archive_items",
            "fields": [
                {
                    "field": "id",
                    "meta": {},
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "status",
                    "meta": {},
                    "schema": {
                        "default_value": "draft"
                    },
                    "type": "string"
                }
            ],
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection")).toBe("test_archive_items");

    // Request Body
    const itemsPostRequestBody = `{
            "status": "draft"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, "data.id")).toBeGreaterThan(0);
    expect(getValue(itemsPostResponse, "data.status")).toBe("draft");

    // Request Body
    const archivePatchRequestBody = `{
            "keys": [
                1
            ]
        }`
    
    // Execute Request
    let archivePatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/archive/{archive}",
        method:"PATCH",
        body:archivePatchRequestBody,
        headers:headers,
        pathParams:{"archive": items}
    });

    // Generated Assertions
    expect(archivePatchResponse.statusCode, 'status code').toBe(200);
    expect(getValue(archivePatchResponse, "data.archived")).toBe(1);
    expect(getValue(archivePatchResponse, "data.keys.0")).not.toBeNull();
    expect(getValue(archivePatchResponse, "data.keys.1")).toBeNull();
    expect(getValue(archivePatchResponse, "data.keys.0")).toBe(getValue(itemsPostResponse, "data.id"));
    expect(getValue(archivePatchResponse, "data.status_field")).toBe("status");

    // Execute Request
    let items1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}/{items_1}",
        method:"GET",
        headers:headers,
        pathParams:{
            "items": items,
            "items_1": items_1
        }
    });

    // Generated Assertions
    expect(items1GetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(items1GetResponse, "data.id")).toBe(getValue(itemsPostResponse, "data.id"));
    expect(getValue(items1GetResponse, "data.status")).toBe("archived");
});

