// Generated by Skyramp v1.3.24 on 2026-05-18 08:45:05.068944319 +0000 UTC m=+286.490172394
// Command: skyramp generate contract rest http://localhost:8055/archive/directus_users \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output archive_system_collection_forbidden_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":["1"]} \
// 		--response-status-code 403 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /archive/directus_users PATCH
test('testDirectusUsersPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const directusUsersPatchRequestBody: string = `{
        "keys": [
            "1"
        ]
    }`;

    // Execute Request
    const directusUsersPatchResponse = await client.sendRequest({
        url: URL,
        path: "/archive/directus_users",
        method: "PATCH",
        body: directusUsersPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusUsersPatchResponse.statusCode, 'status code').toBe(403);
    expect(getValue(directusUsersPatchResponse, "errors.0.extensions.code")).toBe("FORBIDDEN");
    expect(getValue(directusUsersPatchResponse, "errors.1")).toBeNull();
});
