// Generated by Skyramp v1.3.24 on 2026-05-18 08:29:51.104662589 +0000 UTC m=+322.116586696
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output export_json_collection_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_export-json-collection.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let collections = "test_export_items";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_export_items",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "name",
                    "meta": {},
                    "schema": {},
                    "type": "string"
                }
            ],
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers,
        dataOverride:{"collection": collections}
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, 'data.collection')).toBe('test_export_items');

    // Request Body
    const itemsPostRequestBody = `{
            "name": "TestExportItem1"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": collections}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, 'data.name')).toBe('TestExportItem1');
    expect(getValue(itemsPostResponse, 'data.id')).toBeGreaterThan(0);

    // Request Body
    const exportsPostRequestBody = `{
            "format": "json"
        }`
    
    // Execute Request
    let exportsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/exports/{exports}",
        method:"POST",
        body:exportsPostRequestBody,
        headers:headers,
        pathParams:{"exports": collections}
    });

    // Generated Assertions
    expect(exportsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(exportsPostResponse, 'data.0.id')).toBe(getValue(itemsPostResponse, 'data.id'));
    expect(getValue(exportsPostResponse, 'data.0.name')).toBe('TestExportItem1');
    expect(getValue(exportsPostResponse, 'data.1')).toBeNull();

    // Execute Request
    let collectionsCollectionsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections/{collections}",
        method:"DELETE",
        headers:headers,
        pathParams:{"collections": collections}
    });

    // Generated Assertions
    expect(collectionsCollectionsDeleteResponse.statusCode, 'status code').toBe(204);
});

