// Generated by Skyramp v1.3.25 on 2026-05-27 18:33:48.693824883 +0000 UTC m=+0.787773593
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_notifications-read-all-marks-inbox-read.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const notificationsPostRequestBody = `{
            "recipient": "5f88430b-f2d0-4a6c-ad31-452c717f3046",
            "status": "inbox",
            "subject": "Unread-Test-Notification"
        }`

    // Execute Request
    let notificationsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications",
        method:"POST",
        body:notificationsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(notificationsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(notificationsPostResponse, "data.id")).toBeGreaterThan(0);
    expect(getValue(notificationsPostResponse, "data.subject")).toBe("Unread-Test-Notification");
    expect(getValue(notificationsPostResponse, "data.recipient")).toBe("5f88430b-f2d0-4a6c-ad31-452c717f3046");
    expect(getValue(notificationsPostResponse, "data.status")).toBe("inbox");
    expect(getValue(notificationsPostResponse, "data.timestamp")).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Chain ID from POST response
    let id = getValue(notificationsPostResponse, "data.id");

    // Request Body
    const readAllPatchRequestBody = `{}`

    // Execute Request
    let readAllPatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/read-all",
        method:"PATCH",
        body:readAllPatchRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(readAllPatchResponse.statusCode, 'status code').toBe(200);
    expect(getValue(readAllPatchResponse, "data.updated")).toBeGreaterThanOrEqual(1);

    // Execute Request
    let idGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/{id}",
        method:"GET",
        headers:headers,
        pathParams:{"id": id}
    });

    // Generated Assertions
    expect(idGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(idGetResponse, "data.id")).toBe(getValue(notificationsPostResponse, "data.id"));
    expect(getValue(idGetResponse, "data.status")).toBe("read");
    expect(getValue(idGetResponse, "data.subject")).toBe("Unread-Test-Notification");
});

