// Generated by Skyramp v1.3.25 on 2026-06-03 17:50:07.789767255 +0000 UTC m=+370.180219909
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output items_scalar_sort_regression_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_items_scalar_sort_regression.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let collections = "test_scalar_sort_reg";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_scalar_sort_reg",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true,
                        "interface": "numeric",
                        "readonly": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "name",
                    "meta": {
                        "interface": "input"
                    },
                    "schema": {},
                    "type": "string"
                }
            ],
            "meta": {},
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers,
        dataOverride:{"collection": collections}
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection")).toBe("test_scalar_sort_reg");

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Zebra"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": collections}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, "data.id")).toBeGreaterThan(0);
    expect(getValue(itemsPostResponse, "data.name")).toBe("Zebra");

    // Request Body
    const itemsPost1RequestBody = `{
            "name": "Apple"
        }`
    
    // Execute Request
    let itemsPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPost1RequestBody,
        headers:headers,
        pathParams:{"items": collections}
    });

    // Generated Assertions
    expect(itemsPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPost1Response, "data.id")).toBeGreaterThan(0);
    expect(getValue(itemsPost1Response, "data.name")).toBe("Apple");

    // Execute Request
    let itemsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"GET",
        headers:headers,
        pathParams:{"items": collections},
        queryParams:{"sort": ["name"]}
    });

    // Generated Assertions
    expect(itemsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsGetResponse, "data.0.id")).toBe(getValue(itemsPost1Response, "data.id"));
    expect(getValue(itemsGetResponse, "data.0.name")).toBe("Apple");
    expect(getValue(itemsGetResponse, "data.1.id")).toBe(getValue(itemsPostResponse, "data.id"));
    expect(getValue(itemsGetResponse, "data.1.name")).toBe("Zebra");
    expect(getValue(itemsGetResponse, "data.2")).toBeUndefined();

    // Execute Request
    let collectionsCollectionsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections/{collections}",
        method:"DELETE",
        headers:headers,
        pathParams:{"collections": collections}
    });

    // Generated Assertions
    expect(collectionsCollectionsDeleteResponse.statusCode, 'status code').toBe(200);
});

