// Generated by Skyramp v1.3.25 on 2026-05-27 18:34:00.990539865 +0000 UTC m=+0.986315017
// Command: skyramp generate contract rest http://localhost:8055/users/me \
// 		--api-schema /home/runner/work/directus/directus/packages/specs/src/openapi.yaml \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /users/me GET
test('testMeGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body (partial schema for key fields including the new unread_notifications field)
    const expectedMeGetResponseBody: string = `{
        "data": {
            "email": "admin@example.com",
            "first_name": "Admin",
            "id": "5f88430b-f2d0-4a6c-ad31-452c717f3046",
            "last_name": "User",
            "password": "**********",
            "role": "25d9b7a7-6cba-4400-9e63-1cc87526b76b",
            "status": "active",
            "unread_notifications": 0
        }
    }`;

    // Execute Request
    const meGetResponse = await client.sendRequest({
        url: URL,
        path: "/users/me",
        method: "GET",
        headers: headers,
        queryParams: {}
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(meGetResponse, expectedMeGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(meGetResponse, "data.email"), 'email').toBe("admin@example.com");
    expect(getResponseValue(meGetResponse, "data.status"), 'status').toBe("active");
    expect(getResponseValue(meGetResponse, "data.id"), 'id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(meGetResponse, "data.unread_notifications"), 'unread_notifications').toBeGreaterThanOrEqual(0);
});
