// Generated by Skyramp v1.3.23 on 2026-05-11 18:52:59.506822062 +0000 UTC m=+485.584702420
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_move_bulk_sort_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_multi-move-bulk-sort.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let items = "test_skyramp_multi_sort";
    let sort = "sort";

    // Cleanup: delete collection if it exists from a previous run
    await client.sendRequest({
        url:URL_localhost,
        path:"/collections/{collection}",
        method:"DELETE",
        headers:headers,
        pathParams:{"collection": items}
    });

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "test_skyramp_multi_sort",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true,
                        "interface": "input",
                        "readonly": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "sort",
                    "meta": {
                        "interface": "input"
                    },
                    "type": "integer"
                },
                {
                    "field": "name",
                    "meta": {
                        "interface": "input"
                    },
                    "type": "string"
                }
            ],
            "meta": {
                "sort_field": "sort"
            },
            "schema": {}
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers,
        dataOverride:{"meta.sort_field": sort}
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection"), 'collection').toBe("test_skyramp_multi_sort");
    expect(getValue(collectionsPostResponse, "data.meta.sort_field"), 'sort_field').toBe("sort");

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Alpha"
        }`

    // Execute Request (sequential to ensure stable auto-increment ID ordering)
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, "data.name"), 'name').toBe("Alpha");
    expect(getValue(itemsPostResponse, "data.id"), 'id').toBeGreaterThan(0);

    // Request Body
    const itemsPost1RequestBody = `{
            "name": "Beta"
        }`

    // Execute Request
    let itemsPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPost1RequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPost1Response, "data.name"), 'name').toBe("Beta");
    expect(getValue(itemsPost1Response, "data.id"), 'id').toBeGreaterThan(0);

    // Request Body
    const itemsPost2RequestBody = `{
            "name": "Gamma"
        }`

    // Execute Request
    let itemsPost2Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPost2RequestBody,
        headers:headers,
        pathParams:{"items": items}
    });

    // Generated Assertions
    expect(itemsPost2Response.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPost2Response, "data.name"), 'name').toBe("Gamma");
    expect(getValue(itemsPost2Response, "data.id"), 'id').toBeGreaterThan(0);

    // Extract IDs dynamically to ensure correct chaining across sort moves
    const alphaId = getValue(itemsPostResponse, "data.id");
    const betaId = getValue(itemsPost1Response, "data.id");
    const gammaId = getValue(itemsPost2Response, "data.id");

    // Request Body: move Alpha to Beta's position, then Gamma to Alpha's (now-updated) position
    const utils1PostRequestBody = JSON.stringify([
        {"item": alphaId, "to": betaId},
        {"item": gammaId, "to": alphaId}
    ]);

    // Execute Request
    let utils1PostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/{utils}/{utils_1}",
        method:"POST",
        body:utils1PostRequestBody,
        headers:headers,
        pathParams:{
            "utils": sort,
            "utils_1": items
        }
    });

    // Generated Assertions
    expect(utils1PostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let itemsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"GET",
        headers:headers,
        pathParams:{"items": items},
        queryParams:{"sort": [sort]}
    });

    // Generated Assertions — expected final order: Beta, Gamma, Alpha
    expect(itemsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsGetResponse, "data").length, 'item count').toBe(3);
    expect(getValue(itemsGetResponse, "data.0.name"), 'first item name after sort').toBe("Beta");
    expect(getValue(itemsGetResponse, "data.1.name"), 'second item name after sort').toBe("Gamma");
    expect(getValue(itemsGetResponse, "data.2.name"), 'third item name after sort').toBe("Alpha");
    expect(getValue(itemsGetResponse, "data.3"), 'no fourth item').toBeNull();
    expect(getValue(itemsGetResponse, "data.0.id"), 'first item id chained').toBe(getValue(itemsPost1Response, "data.id"));
    expect(getValue(itemsGetResponse, "data.1.id"), 'second item id chained').toBe(getValue(itemsPost2Response, "data.id"));
    expect(getValue(itemsGetResponse, "data.2.id"), 'third item id chained').toBe(getValue(itemsPostResponse, "data.id"));
});

