// Generated by Skyramp v1.3.24 on 2026-05-19 18:09:14.330065489 +0000 UTC m=+651.428852422
// Command: skyramp generate contract rest http://localhost:8055/notifications/read-all \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output notifications_read_all_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--response-data {"data":{"updated":0}} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /notifications/read-all PATCH
test('testReadAllPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedReadAllPatchResponseBody: string = `{
        "data": {
            "updated": 0
        }
    }`;

    // Execute Request
    const readAllPatchResponse = await client.sendRequest({
        url: URL,
        path: "/notifications/read-all",
        method: "PATCH",
        headers: headers
    });

    // Generated Assertions
    expect(readAllPatchResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(readAllPatchResponse, expectedReadAllPatchResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(readAllPatchResponse, "data.updated"), 'updated count').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(readAllPatchResponse, "data.updated"), 'updated count value').toBe(0);
});
