// Generated by Skyramp v1.3.25 on 2026-05-27 18:27:00.28421753 +0000 UTC m=+1.122925729
// Command: skyramp generate contract rest http://localhost:8055/utils/sort/{collection} \
// 		--api-schema /home/runner/work/directus/directus/packages/specs/src/openapi.yaml \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--path-params collection=articles \
// 		--provider \
// 		--request-data [{"item":1,"to":2},{"item":3,"to":4}] \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/sort/{collection} POST
test('testSortCollectionPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const collection = "articles";

    // Request Body
    const sortCollectionPostRequestBody: string = `[
        {
            "item": 1,
            "to": 2
        },
        {
            "item": 3,
            "to": 4
        }
    ]`;

    // Execute Request
    const sortCollectionPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/sort/{collection}",
        method: "POST",
        body: sortCollectionPostRequestBody,
        headers: headers,
        pathParams: {"collection": collection}
    });

    // Generated Assertions
    expect(sortCollectionPostResponse.statusCode, 'status code').toBe(200);
    // No response body is returned for a successful sort operation (empty 200 response)
    expect(getValue(sortCollectionPostResponse, 'errors')).toBeUndefined();
    expect(getValue(sortCollectionPostResponse, 'errors.0')).toBeUndefined();
});
