// Generated by Skyramp v1.3.24 on 2026-05-13 00:21:35.40964669 +0000 UTC m=+444.154113503
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_bulk_array_multiple_moves_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_sort-bulk-array-multiple-moves.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const foldersPostRequestBody = `{
            "name": "test-sort-folder-a"
        }`
    
    // Execute Request
    let foldersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/folders",
        method:"POST",
        body:foldersPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(foldersPostResponse, "data.name")).toBe("test-sort-folder-a");
    expect(getValue(foldersPostResponse, "data.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const foldersPost1RequestBody = `{
            "name": "test-sort-folder-b"
        }`
    
    // Execute Request
    let foldersPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/folders",
        method:"POST",
        body:foldersPost1RequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(foldersPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(foldersPost1Response, "data.name")).toBe("test-sort-folder-b");
    expect(getValue(foldersPost1Response, "data.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    const folderId1 = getValue(foldersPostResponse, "data.id");
    const folderId2 = getValue(foldersPost1Response, "data.id");

    // Request Body
    const directusFoldersPostRequestBody = `[{"item":"${folderId1}","to":"${folderId2}"}]`
    
    // Execute Request
    let directusFoldersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/sort/directus_access",
        method:"POST",
        body:directusFoldersPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(directusFoldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(directusFoldersPostResponse, "errors")).toBeUndefined();
});

