// Generated by Skyramp v1.3.24 on 2026-05-19 18:06:17.677155443 +0000 UTC m=+556.984285956
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_bulk_array_moves_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_sort-bulk-array-moves.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let collections = "sort_bulk_test";
    let items_1 = "3";
    let items_1_1 = "2";
    let utils = "sort";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "sort_bulk_test",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "name",
                    "type": "string"
                },
                {
                    "field": "sort",
                    "type": "integer"
                }
            ],
            "meta": {
                "sort_field": "sort"
            }
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers,
        dataOverride:{"collection": collections}
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection"), 'collection name').toBe("sort_bulk_test");

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Item One"
        }`
    
    // Request Body
    const itemsPost1RequestBody = `{
            "name": "Item Two"
        }`
    
    // Request Body
    const itemsPost2RequestBody = `{
            "name": "Item Three"
        }`
    
    const [itemsPostResponse, itemsPost1Response, itemsPost2Response] = await Promise.all([
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}",
            method: "POST",
            body: itemsPostRequestBody,
            headers: headers,
            pathParams: {"items": collections}
        }),
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}",
            method: "POST",
            body: itemsPost1RequestBody,
            headers: headers,
            pathParams: {"items": collections}
        }),
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}",
            method: "POST",
            body: itemsPost2RequestBody,
            headers: headers,
            pathParams: {"items": collections}
        }),
    ]);

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);    // Generated Assertions
    expect(itemsPost1Response.statusCode, 'status code').toBe(200);    // Generated Assertions
    expect(itemsPost2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(itemsPostResponse, "data.id"), 'item 1 id').toBeGreaterThan(0);
    expect(getResponseValue(itemsPostResponse, "data.name"), 'item 1 name').toBe("Item One");
    expect(getResponseValue(itemsPost1Response, "data.id"), 'item 2 id').toBeGreaterThan(0);
    expect(getResponseValue(itemsPost1Response, "data.name"), 'item 2 name').toBe("Item Two");
    expect(getResponseValue(itemsPost2Response, "data.id"), 'item 3 id').toBeGreaterThan(0);
    expect(getResponseValue(itemsPost2Response, "data.name"), 'item 3 name').toBe("Item Three");

    // Request Body
    const utils1PostRequestBody = `[
            {
                "item": 3,
                "to": 1
            },
            {
                "item": 2,
                "to": 3
            }
        ]`
    
    // Execute Request
    let utils1PostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/{utils}/{utils_1}",
        method:"POST",
        body:utils1PostRequestBody,
        headers:headers,
        pathParams:{
            "utils": utils,
            "utils_1": collections
        }
    });

    // Generated Assertions
    expect(utils1PostResponse.statusCode, 'status code').toBe(200);

    const [items1DeleteResponse, items1Delete1Response, items1Delete2Response] = await Promise.all([
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}/{items_1}",
            method: "DELETE",
            headers: headers,
            pathParams: {
                "items": collections,
                "items_1": items_1
            }
        }),
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}/{items_1}",
            method: "DELETE",
            headers: headers,
            pathParams: {
                "items": collections,
                "items_1": items_1_1
            }
        }),
client.sendRequest({
            url: URL_localhost,
            path: "/items/{items}/{items_1}",
            method: "DELETE",
            headers: headers,
            pathParams: {
                "items": collections,
                "items_1": getResponseValue(itemsPostResponse, "data.id")
            }
        }),
    ]);

    // Generated Assertions
    expect(items1DeleteResponse.statusCode, 'status code').toBe(204);    // Generated Assertions
    expect(items1Delete1Response.statusCode, 'status code').toBe(204);    // Generated Assertions
    expect(items1Delete2Response.statusCode, 'status code').toBe(204);

    // Execute Request
    let collectionsCollectionsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections/{collections}",
        method:"DELETE",
        headers:headers,
        pathParams:{"collections": collections}
    });

    // Generated Assertions
    expect(collectionsCollectionsDeleteResponse.statusCode, 'status code').toBe(204);
});

