// Generated by Skyramp v1.3.24 on 2026-05-19 18:06:07.344249221 +0000 UTC m=+546.651379724
// Command: skyramp generate contract rest http://localhost:8055/utils/sort/directus_users \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output sort_unauthorized_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--request-data {"item":1,"to":2} \
// 		--response-status-code 403 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/sort/directus_users POST
test('testDirectusUsersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // No auth header intentionally — tests that unauthenticated requests are rejected
    const headers: Record<string, string> = {};

    // Request Body
    const directusUsersPostRequestBody: string = `{
        "item": 1,
        "to": 2
    }`;

    // Execute Request
    const directusUsersPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/sort/directus_users",
        method: "POST",
        body: directusUsersPostRequestBody,
        headers: headers
    });

    // Generated Assertions — unauthenticated request must be rejected (401 or 403)
    expect([401, 403], 'unauthenticated sort must be rejected').toContain(directusUsersPostResponse.statusCode);
    expect(getValue(directusUsersPostResponse, "errors.0"), 'error object present').not.toBeNull();
    expect(getValue(directusUsersPostResponse, "errors.0.extensions.code"), 'error code present').toBeTruthy();
    expect(getValue(directusUsersPostResponse, "errors.1"), 'only one error returned').toBeUndefined();
});
