// Generated by Skyramp v1.3.24 on 2026-05-19 18:06:15.783007218 +0000 UTC m=+555.090137731
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_single_backward_compat_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_sort-single-backward-compat.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let collections = "sort_compat_test";
    let items_1 = "2";
    let items_1_1 = "1";
    let utils = "sort";

    // Request Body
    const collectionsPostRequestBody = `{
            "collection": "sort_compat_test",
            "fields": [
                {
                    "field": "id",
                    "meta": {
                        "hidden": true
                    },
                    "schema": {
                        "has_auto_increment": true,
                        "is_primary_key": true
                    },
                    "type": "integer"
                },
                {
                    "field": "name",
                    "type": "string"
                },
                {
                    "field": "sort",
                    "type": "integer"
                }
            ],
            "meta": {
                "sort_field": "sort"
            }
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers,
        dataOverride:{"collection": collections}
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(collectionsPostResponse, "data.collection"), 'collection name').toBe("sort_compat_test");

    // Request Body
    const itemsPostRequestBody = `{
            "name": "Alpha Item"
        }`
    
    // Execute Request
    let itemsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPostRequestBody,
        headers:headers,
        pathParams:{"items": collections}
    });

    // Generated Assertions
    expect(itemsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPostResponse, "data.id"), 'alpha item id').toBeGreaterThan(0);
    expect(getValue(itemsPostResponse, "data.name"), 'alpha item name').toBe("Alpha Item");

    // Request Body
    const itemsPost1RequestBody = `{
            "name": "Beta Item"
        }`
    
    // Execute Request
    let itemsPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}",
        method:"POST",
        body:itemsPost1RequestBody,
        headers:headers,
        pathParams:{"items": collections}
    });

    // Generated Assertions
    expect(itemsPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(itemsPost1Response, "data.id"), 'beta item id').toBeGreaterThan(0);
    expect(getValue(itemsPost1Response, "data.name"), 'beta item name').toBe("Beta Item");

    // Request Body
    const utils1PostRequestBody = `{
            "item": 2,
            "to": 1
        }`
    
    // Execute Request
    let utils1PostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/{utils}/{utils_1}",
        method:"POST",
        body:utils1PostRequestBody,
        headers:headers,
        pathParams:{
            "utils": utils,
            "utils_1": collections
        }
    });

    // Generated Assertions
    expect(utils1PostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let items1DeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}/{items_1}",
        method:"DELETE",
        headers:headers,
        pathParams:{
            "items": collections,
            "items_1": items_1
        }
    });

    // Generated Assertions
    expect(items1DeleteResponse.statusCode, 'status code').toBe(204);

    // Execute Request
    let items1Delete1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/items/{items}/{items_1}",
        method:"DELETE",
        headers:headers,
        pathParams:{
            "items": collections,
            "items_1": items_1_1
        }
    });

    // Generated Assertions
    expect(items1Delete1Response.statusCode, 'status code').toBe(204);

    // Execute Request
    let collectionsCollectionsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/collections/{collections}",
        method:"DELETE",
        headers:headers,
        pathParams:{"collections": collections}
    });

    // Generated Assertions
    expect(collectionsCollectionsDeleteResponse.statusCode, 'status code').toBe(204);
});

