// Generated by Skyramp v1.3.24 on 2026-05-13 00:20:01.292828149 +0000 UTC m=+350.037294962
// Command: skyramp generate contract rest http://localhost:8055/utils/sort/directus_folders \
// 		--api-schema /home/runner/work/directus/directus/packages/specs/src/openapi.yaml \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output sort_array_format_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--request-data [{"item":"1","to":"2"}] \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/sort/directus_folders POST
test('testDirectusFoldersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const directusFoldersPostRequestBody: string = `[
        {
            "item": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "to": "b2c3d4e5-f6a7-8901-bcde-f12345678901"
        }
    ]`;

    // Execute Request
    const directusFoldersPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/sort/directus_access",
        method: "POST",
        body: directusFoldersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusFoldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(directusFoldersPostResponse, "errors")).toBeUndefined();
});
