// Generated by Skyramp v1.3.23 on 2026-05-11 18:36:39.395008217 +0000 UTC m=+510.196653752
// Command: skyramp generate contract rest http://localhost:8055/utils/sort/directus_dashboards \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output sort_empty_array_validation_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/sort/directus_dashboards POST
test('testDirectusDashboardsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const directusDashboardsPostRequestBody: string = `[]`;

    // Execute Request
    const directusDashboardsPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/sort/directus_dashboards",
        method: "POST",
        body: directusDashboardsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusDashboardsPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(directusDashboardsPostResponse, "errors.0.message"), 'error message').toBe("Invalid payload. \"value\" must contain at least 1 items.");
    expect(getValue(directusDashboardsPostResponse, "errors.0.extensions.code"), 'error code').toBe("INVALID_PAYLOAD");
    expect(getValue(directusDashboardsPostResponse, "errors.1"), 'no second error').toBeNull();
});

// contract test for /utils/sort/directus_dashboards POST with array item missing required 'to' field
test('testDirectusDashboardsPostInvalidArrayItem', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body — array item missing required 'to' field
    const directusDashboardsPostRequestBody: string = `[{"item": 1}]`;

    // Execute Request
    const directusDashboardsPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/sort/directus_dashboards",
        method: "POST",
        body: directusDashboardsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(directusDashboardsPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(directusDashboardsPostResponse, "errors.0.message"), 'error message').toBe("Invalid payload. \"[0].to\" is required");
    expect(getValue(directusDashboardsPostResponse, "errors.0.extensions.code"), 'error code').toBe("INVALID_PAYLOAD");
    expect(getValue(directusDashboardsPostResponse, "errors.1"), 'no second error').toBeNull();
});
