// Generated by Skyramp v1.3.25 on 2026-06-03 18:08:00.028738281 +0000 UTC m=+278.189099725
// Command: skyramp generate contract rest http://localhost:8055/webhooks \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output webhook_post_contract_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--provider \
// 		--request-data {"url":""} \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /webhooks POST
test('testWebhooksPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const webhooksPostRequestBody: string = `{
        "url": ""
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL,
        path: "/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(webhooksPostResponse, "errors.0.message")).toBe("Invalid payload. Field \"url\" is required.");
    expect(getValue(webhooksPostResponse, "errors.0.extensions.code")).toBe("INVALID_PAYLOAD");
    expect(getValue(webhooksPostResponse, "errors.1")).toBeUndefined();
});
