// Generated by Skyramp v1.3.25 on 2026-06-03 18:08:10.652134931 +0000 UTC m=+288.812496375
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhook_create_list_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_webhook-create-list.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const webhooksPostRequestBody = `{
            "collections": [
                "articles"
            ],
            "method": "POST",
            "url": "https://example.com/webhook-handler"
        }`
    
    // Execute Request
    let webhooksPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/webhooks",
        method:"POST",
        body:webhooksPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(201);
    expect(getValue(webhooksPostResponse, "data")).toBeGreaterThan(0);

    // Execute Request
    let webhooksGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/webhooks",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(webhooksGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(webhooksGetResponse, "data").length).toBeGreaterThan(0);
    expect(getValue(webhooksGetResponse, "data.0.id")).toBe(getValue(webhooksPostResponse, "data"));
    expect(getValue(webhooksGetResponse, "data.0.url")).toBe("https://example.com/webhook-handler");
    expect(getValue(webhooksGetResponse, "data.0.method")).toBe("POST");
    expect(getValue(webhooksGetResponse, "data.0.collections.0")).toBe("articles");
});

