// Generated by Skyramp v1.3.25 on 2026-06-03 18:08:12.760380945 +0000 UTC m=+290.920742399
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhook_delete_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_webhook-delete-lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let webhooks = "1";

    // Request Body
    const webhooksPostRequestBody = `{
            "collections": [
                "articles"
            ],
            "method": "GET",
            "url": "https://example.com/delete-test-webhook"
        }`
    
    // Execute Request
    let webhooksPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/webhooks",
        method:"POST",
        body:webhooksPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(201);
    expect(getValue(webhooksPostResponse, "data")).toBeGreaterThan(0);

    // Execute Request
    let webhooksWebhooksDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/webhooks/{webhooks}",
        method:"DELETE",
        headers:headers,
        pathParams:{"webhooks": webhooks}
    });

    // Generated Assertions
    expect(webhooksWebhooksDeleteResponse.statusCode, 'status code').toBe(204);
});

